### ISSUE TITLE
Feature Request: Make snapshots atomic relative to one another

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#104]
I use multiple virtual disks per VM/CT. They are in the same tree (rpool/data/vms/snap-15/vm-100-disk-[1|2] for example). Sanoid takes snapshots one at a time, so disk-1 is not atomic with disk-2

The new syncoid "--no-sync-snap" option takes care of part of it.

**Comment by jimsalterjrs** [comment]
This isn't ever going to be a default, but I should be able to implement it as a configurable policy option at some point.  Probably `recursion=atomic` or something similar in `sanoid.conf` for the parent dataset.

Note that setting such a `recursion=atomic` option would make any attempt to change some policies on child datasets fruitless.  The reason I wasn't already using atomic recursion (ie `zfs snapshot -r` rather than individually taking snapshots) is because I wanted the ability to set a sweeping policy on a parent dataset while still modifying it for child datasets.

**Comment by redmop** [comment]
You can do multiple snapshots per zfs run and they are atomic relative to one another.

`zfs snapshot data/home/redmop@snap1 data/home/jimsalterjrs@snap2`

**Comment by jimsalterjrs** [comment]
... holy shit I had no idea you could do that. I thought you had to do `zfs snapshot -r` to get atomic snapshots across datasets.

Any chance you could take a look at the code and issue a PR?  This shouldn't be too difficult, but I'm done writing code for the day. =)  If you can't/won't, I'll pick this up again later.  Right now I'm just closing out my notifications one by one though.

**Comment by redmop** [comment]
I'll put it on my weekend playlist. I have a server that I'm about to nuke, so it's a nice fun playground.

**Comment by TerraTech** [comment]
@redmop @jimsalterjrs Has there been any progress on this since 7/2017?

_To note, I'm being liberal with the 'snapshot' naming for illustrative purposes._

I would really like to see atomic snapshots as my use case is just handling it all from the root pool.
e.g.  zfs snapshot -r zpool@syncoid_20181222-04:05:06

This would help me to see exactly what datasets on the target server were exactly in the same backup session.
e.g. (where zpool/b/c was recently destroyed on source)
**zpool/a/b@syncoid_20181222-04:05:06 (same session)**
_zpool/b/c@syncoid_20181218-01:02:03 (destroyed on source but still on target)_
**zpool/g/h@syncoid_20181222-04:05:06 (same session)**

Then to drill down into it:
$ zfs list -tsnap -r zpool | grep '@syncoid_20181222-04:05:06'

The key to this is a consistent atomic snapshot across all of source hierarchy.

An alternative is to take 2 snapshots at the beginning of the syncoid backup session, one at the root (recursive) and the existing style that is used now.
$ zfs snapshot -r zpool@syncoid_**session**_20181222-04:05:06

> The reason I wasn't already using atomic recursion (ie zfs snapshot -r rather than individually taking snapshots) is because I wanted the ability to set a sweeping policy on a parent dataset while still modifying it for child datasets.

A hybrid (outside the box) solution is to use a snapshot/bookmark combo.  Where snapshots are done as they are now, but create a consistent session bookmark against each snapshot.  This is ultra cheap and really doesn't get in the way of anything.
```
(pseudo)
consistent_snapshot=syncoid_session_20181222-04:05:06  (taken at start of run)
$ zfs snapshot zpool/a/b/c@syncoid_20181222-04:15:16  (current date/time)
$ zfs bookmark zpool/a/b/c@syncoid_20181222-04:15:16 zpool/a/b/c#syncoid_${consistent_snapshot} 
(next set)
$ zfs snapshot zpool/d/e/f@syncoid_20181222-05:19:22  (current date/time)
$ zfs bookmark zpool/a/b/c@syncoid_20181222-05:19:22 zpool/a/b/c#syncoid_${consistent_snapshot} 

Then if I just want to see a session set:
$ zfs list -tbookmark -r zpool | grep #syncoid_20181222-04:05:06
```

Personally, I think the snapshot/bookmark combo would work the best, because even if the snapshot is pruned later, the bookmark would still remain.  Bookmark management could be wired in as well, for retention control or just keep only the current session bookmark.  e.g. ```--retain-session-bookmarks=5```  to retain the last 5 bookmarks, where the default would be ```1```.

FWIW, I'm already looking at how to wire this (snapshot+bookmark combo) into syncoid as an in-house customization for our backup procedures.  I ran across this issue, so I just thought I'd layout the internal direction that FutureQuest was going with this because it was an itch that needed scratched for enterprise level retention naming.  :)

**Comment by TerraTech** [comment]
@redmop @jimsalterjrs I have just pushed a new branch that is a 1st draft POC and is based on the v2.0.1 stable release.
https://github.com/TerraTech/sanoid/commit/17badeeed1a912b513248c41ac00ebfe94d69db6

It creates the (_consistent_) session bookmarks properly on both source and target systems.  However, it only taps into one send/receive location, which is the codepath my tests were taking.

If this is something you like, I can work on a full implementation that taps into all relevant areas.  Management of the bookmarks (auto purging) will be added somewhere down the line when I have more available time.

**Comment by TerraTech** [comment]
Ignore the $mbufferoptions tweak, I plan on creating a new switch to control its '-m' value, e.g. --mbuffer-size=1G or --mbuffer-size=25%, etc...  I didn't feel like doing yet another forced push to remove it since its only POC.

**Comment by TerraTech** [comment]
A quick little helper command to visually match up the bookmark to snapshot
```sh
$ zfs list -tsnap,bookmark -H -ocreatetxg,name | egrep '[@#]syncoid_' | sort -b -k1,1 -k2,2
```
Bookmarks are nothing more than a recording of a snapshot's transaction group creation value (createtxg) which are atomic/unique in nature.
