### ISSUE TITLE
Question: How to use sand in combination with syncoid

### ISSUE THREAD

**Issue by dkruyt** [jimsalterjrs/sanoid#116]
I am a little confused how to use sand and synced together.

I have setup sanoid, this works fine by it self. the same for syncoid.

No I use syncoid on a volume where sanoid takes hourly, daily and monthly snaps. Then the hourly autosnaps also are synced but never been pruned on the target site by syncoid. Am I missing something conceptual here?

**Comment by jimsalterjrs** [comment]
Syncoid does not prune snapshots (with the exception of old sync snapshots, if you're using them).

If you want a snapshot removal policy on your target, you need to run `sanoid` on your target, just like you do on your source.  You'll want to set `autosnap=no` and `autoprune=yes` on the target's `sanoid.conf`, and if you use the monitoring functionality, you'll probably want to dial back your warnings and crits on the target to sane values for your replication frequency - check the `[template_backup]` in the reference `sanoid.conf` to see what I mean (or just use that template directly).

**Comment by dkruyt** [comment]
Ah, I can use sanoid on the target to prune those. But how would I setup the following then?
Using sanoid on source site to have sort time backups and a replica target for archiving?


source[sanoid - 4h, 7d] -- syncoid 1 per day --> target[sanoid 7d, 12m]

I tested this setup, but syncoid removes the target sanoids autosnaps.

**Comment by jimsalterjrs** [comment]
Syncoid does not remove any snapshot that does not follow the regex `syncoid_$localhostname_$datestamp`, period.

After successful replication, `syncoid` removes all snapshots for replicated datasets which match the regex `syncoid_$localhostname_$datestamp` *except* the one which was used for replication just then.

Now, *sanoid* itself will of course remove snapshots, and it'll do so potentially every time it's called from cron.  I suspect you just haven't looked at your snapshot retention policies in `sanoid.conf` on your target machine closely enough.

**Comment by dkruyt** [comment]
I already looked at the code, that is clear to me.

But if I look at https://github.com/jimsalterjrs/sanoid/issues/60 it Sounds like someone had the same question and is already answered there.

**Comment by kpande** [comment]
this is overly complicated considering that `send -R` | `recv -F` will auto-prune snapshots that don't exist on the sending node.

**Comment by jimsalterjrs** [comment]
> `send -R | recv -F` will auto-prune snapshots that don't exist on the sending node.

@kpande no, it will not. `recv -F` will remove snapshots that _would otherwise prevent replication_; it will *not* prune all snapshots from the target that don't exist on the source.

~~~~
root@archivist:~# zfs list -rt snap data/backup/banshee/opt | head -n 2
NAME                                                               USED  AVAIL  REFER  MOUNTPOINT
data/backup/banshee/opt@autosnap_2017-04-01_00:00:02_monthly     8K      -   283G  -
root@archivist:~# 
~~~~

The target has a monthly snapshot for 2017-04-01.

~~~~
root@banshee:/images# zfs list -rt snap banshee/opt | grep 2017-04
root@banshee:/images# 
~~~~

The source does not have such a snapshot.

~~~~
root@banshee:/images# zfs send -I banshee/opt@autosnap_2017-08-01_23:59:01_daily banshee/opt@autosnap_2017-08-04_12:00:01_hourly | pv | ssh 192.168.100.10 zfs receive -F data/backup/banshee/opt
12.4MiB 0:00:01 [10.9MiB/s] [       <=>                                                                                        ]
~~~~

After replication, the snapshot which was not present on the source is still present on the target, and has not been removed by -F.

~~~~
root@archivist:~# zfs list -rt snap data/backup/banshee/opt | head -n 2
NAME                                                               USED  AVAIL  REFER  MOUNTPOINT
data/backup/banshee/opt@autosnap_2017-04-01_00:00:02_monthly     8K      -   283G  -
~~~~

Please be a little more careful when you're dropping comments on these bugs, and test your theories before posting. You're batting .000 so far, and it takes time and effort to correct your errors, and decreases the signal:noise on the thread.

**Comment by kpande** [comment]
you must use `send -R` as I described above. I'm a ZFSOnLinux project member, I really do know what I'm talking about. Please re-test.

**Comment by kpande** [comment]
from zfs man page:

```
    recv
           -F

               Force  a rollback of the file system to the most recent snapshot before performing the receive operation. ***If receiving an incremental replication stream (for example, one generated by zfs send -R -[iI]), destroy snap‐
               shots and file systems that do not exist on the sending side.***

```

**Comment by kpande** [comment]
for the record, `send -R` would also link clones as requested in another PR here.

**Comment by jimsalterjrs** [comment]
Interesting; I see that you're correct about `send -RI` piped to `receive -F` as opposed to `send -I` to `receive -F`. I have to admit, that's pretty unexpected behavior. Unfortunately, it isn't really useful here, and very, very much does not represent behavior I want.

`zfs send -R` is recursive, and I don't actually want a recursive send here - it presents problems fairly frequently when child datasets are created or deleted on the source after the target is already established, among other problems.  This stopped me from using `-R` in syncoid very early on.

Even if this were fixed, it doesn't solve a larger problem - I don't _want_ snapshots to be destroyed on the target merely because they're no longer present on the source. I very frequently have a source which is on fast, small SSD and a target which is on slow, large rust, and wish to be able to keep a greater archive depth on the target than I can afford to fit on the source.  Using -R would make that impossible.

**Comment by kpande** [comment]
you can `zfs hold` snapshots you wish to keep on receiving side.

**Comment by kpande** [comment]
for the other issues you describe, compare GUIDs to discover renamed datasets.

**Comment by jimsalterjrs** [comment]
> I'm not going to ask for an apology, but maybe be less rude.

I've got no problem offering an apology - I'm sorry I misjudged your ZFS knowledge level. 

I'd still like you to maybe pay a little more attention to what's going on here before you drop seemingly-authoritative bombs in threads. From the other thread, `zfs send -P` is no kidding inaccurate, and in this thread, you don't seem familiar with a lot of _my_ project's goals.  I very much welcome your input, but it could be a little more constructive.

If you'd like to submit a PR utilising `send -R | recv -F` and holds and trying to handle `-R` failing when datasets are newly created or destroyed under the parent when updating prior incrementals, I'd be happy to review it. Right now, I'm not sure I really see what I'm gaining from rewriting all that, and from the sound of it, including quite a lot of complexity.  Particularly when it sounds like you're asking me to `zfs hold` literally *every* snapshot on the target, just to keep `-R` from wiping it out, when my desired MO is very literally to run sanoid on both sides.

A `syncoid --destructive` to use -R/-F to deliberately wipe out no longer existing snapshots on the target might be a useful option without disrupting the existing main use case. It's not something *I'm* particularly interested in using, though, so again that would be a case of "you're welcome to open a PR if you'd like to have that feature".
