### ISSUE TITLE
Sanoid should be able to have wildcards in path locations

### ISSUE THREAD

**Issue by LordAro** [jimsalterjrs/sanoid#124]
Unless I'm very much mistaken, sanoid does not support wildcards in the path locations, such as `[tank/foo*bar]`

My use case is that I'm using sanoid to take snapshots of lxd containers (#121 looks nice as well, in that regard) and don't wish to backup "test" containers, i.e. those ending in "-test", so I'd like to be able to specify `[tank/guests/*-test]` with the "unmanaged" template (as suggested by you [here](https://www.reddit.com/r/zfs/comments/6i7eqw/sanoid_exclude_children_from_snapshots/dj50v8a/))

**Comment by jimsalterjrs** [comment]
You are correct; wildcards are not supported.

I would strongly recommend that rather than introducing wildcards - which can be a spectacular way to screw up, and with REALLY large sets of data, given that we're working with entire ZFS datasets here - you just organize your datasets a little more cleanly - ie, `tank/guests/test/guest1`, `tank/guests/test/guest2` and so forth.

I haven't played with LXD yet, so I'm not sure how easy or difficult that is to do with lxd's built-in commands. If that's hard, maybe you can educate me a little?

**Comment by jimsalterjrs** [comment]
Assigning to @LordAro, blocking until I hear back whether organizing "test" guests under a "test" parent dataset is possible for your workload.

**Comment by LordAro** [comment]
Right, so it looks like there is a way to do this with LXD - storage volumes. These can be created and specified when the container is created, and so can be excluded from the backup procedures in the "usual" manner.

Unfortunately, because I'm managing our containers with Ansible and there's not currently a way to move it across storage pools (lxc/lxd#3315) when you do the copy (have to do it afterwards with manual config editing), this solution is not viable for me. Failing anything else, I'll generate the san/syncoid config using the Ansible inventories

**Comment by a-schaefers** [comment]
I have a use case at work which could use wildcards as well. I do not believe, "...introducing wildcards - which can be a spectacular way to screw up, and with REALLY large sets of data" is a good enough reason to block this feature request.
