### ISSUE TITLE
Dataset with no snapshots breaks syncoid with --no-sync-snap

### ISSUE THREAD

**Issue by LordAro** [jimsalterjrs/sanoid#127]
I've (attempted to) exclude a dataset from being snapshotted by sanoid, and from being replicated with syncoid (1.4.14)

```ini
[tank]
    use_template = default
    recursive = yes
[tank/excludeddataset]
    use_template = excluded
    recursive = yes

[template_excluded]
    autosnap = no
    autoprune = no
    monitor = no
```

However, syncoid, with the --no-sync-snap option, balks at the dataset, dying on: `CRIT: --no-sync-snap is set, and getnewestsnapshot() could not find any snapshots on source!`

(as an aside, it was difficult to work out which dataset this applied to - it's just not in the output anywhere, error message or otherwise - can this be amended?)

This corresponds to [this line](https://github.com/jimsalterjrs/sanoid/blob/32cd10097383c2568cf8d285a1a7f68167edd1c0/syncoid#L666), which I believe shouldn't be a `die` as changing it to a warn, as is a similar statement on [line 174](https://github.com/jimsalterjrs/sanoid/blob/32cd10097383c2568cf8d285a1a7f68167edd1c0/syncoid#L174), makes the script complete as expected.

Unless I'm doing something wrong with how I'm excluding datasets (can we have a provided excluded template as well?) this would seem to be a bug, as syncoid shouldn't be trying to copy a dataset with no snapshots, with the excluded template, anyway.

**Comment by jimsalterjrs** [comment]
Interesting! It hadn't occurred to me to try to exclude replication of a particular dataset within a recursive syncoid call (you didn't specify recursion, but I assume that's what you're trying to do, since otherwise `die`ing wouldn't be a problem).

If you want to change the `die` to a `warn`, and QA it to make sure it works properly both inside a recursive call (ie, completes the rest of the stuff) and outside a recursive call (ie, just aborts, since you asked for `--no-sync-snap` on a dataset with no existing snapshots), I'd be happy to take a PR.

I'd also accept a PR for your `[template_excluded]` to the dist version of `sanoid.conf`. I can see where that would be handy. Although... hrm. I think naming it `[template_ignore]` might be more intuitive. What do you think?

**Comment by LordAro** [comment]
I'll have a play around. "ignore" sounds better to me as well. By dist version, do you mean sanoid.defaults.conf or sanoid.conf?

**Comment by jimsalterjrs** [comment]
I mean the `sanoid.conf` provided with a clean download.

Right now I'm not implementing any templates in `sanoid.defaults.conf`. I've considered doing that, but I don't want to make things less discoverable / potentially do really interesting things to break people's running configs if they update their `sanoid.defaults.conf`.
