### ISSUE TITLE
feature suggestion: snapshot naming convention to match samba vfs naming

### ISSUE THREAD

**Issue by jasonblewis** [jimsalterjrs/sanoid#135]
Shadow copies are a feature of Microsof Windows that allows the user to restore previous versions of a file.

If snapshots were named the same as the samba VFS shadow copy format, we'd get vfs shadow copies for free in samba.

samba expects snapshots to be named: @GMT-YYYY.MM.DD-hh.mm.ss

see https://manpages.debian.org/stretch/samba-vfs-modules/vfs_shadow_copy.8.en.html

**Comment by jasonblewis** [comment]
since raising this issue. I found out some more info that may be relevant.

You can change the format samba expects for the naming of snapshots using `shadow:format = format` option. https://manpages.debian.org/stretch/samba-vfs-modules/vfs_shadow_copy2.8.en.html

**Comment by jimsalterjrs** [comment]
This also assumes the vfs patch for Samba actually works on your distro (or that you're willing to compile it in from source for yourself); when I looked into doing this on Ubuntu I discovered that Ubuntu's samba binaries had not been compiled so as to support it. Sadface.

Regardless, you're right; you can set shadow:format to make Sanoid snapshots work - which is what I would recommend, rather than muddying up Sanoid's scheme itself.

**Comment by jasonblewis** [comment]
Regarding it not being compiled in, did you try `sudo apt install samba-vfs-modules`?

Another point to consider is that having snapshots with words like daily, hourly in them means you can't use all the snapshots for the VFS. you'll only be able to use one of the sets.

**Comment by jasonblewis** [comment]
related to #142
