### ISSUE TITLE
Cap syncoid to specific throughput?

### ISSUE THREAD

**Issue by ewwhite** [jimsalterjrs/sanoid#146]
Due to 95th percentile billing at one of my datacenters, I need to cap certain syncoid transfers to 30 Megabits/second.

It's not immediately clear how to achieve this. The source and target bwlimit options seem to control mbuffer. Should I be setting one of these parameters to 3M (3 Megabytes/sec)? Trying that produces a command line like `/usr/bin/mbuffer -r 3M -q -s 128k -m 16M` - Is this right?

 The resulting traffic appears bursty at the network level, and the bandwidth limit definitely isn't honored.

**Comment by jimsalterjrs** [comment]
--source-bwlimit and --target-bwlimit do control mbuffer on source and target. Assuming you HAVE mbuffer on the side you're invoking the bwlimit, it absolutely does work; I use source-bwlimit to avoid oversaturating uplink on 90+% of the locations I manage.

**Comment by ewwhite** [comment]
Please provide an example to achieve the 30 Megabits/second limit.

Syncoid and mbuffer are present on both sides. I pull the data (on target) from the source.

**Comment by jimsalterjrs** [comment]
syncoid --source-bwlimit=3M root@remote:pool/dataset pool/dataset --compress=gzip

Note that you will typically see what appears to be MUCH faster than 3MB/sec throughout, because you're seeing the throughput at the uncompressed data level, not at the network level. Ditto with no compression flag set at all, because default is lzo compression.

If you want to reassure yourself what's happening, you can run iftop on one side to see how much actual network bandwidth is being consumed - or do a trial run with --compress=none, if you don't have iftop or similar available.

**Comment by MynaITLabs** [comment]
Note:   Conversation above is in bps (BITS per second)  and the bwlimit parameter takes Bps (BYTES per second), a factor of 8 difference.

[--source-bwlimit=<limit k|m|g|t>](https://manpages.debian.org/testing/sanoid/syncoid.8.en.html#source)
Bandwidth limit in bytes/kbytes/etc per second on the source transfer
