### ISSUE TITLE
Sanoid and Synoid - Snapshots taken by this script are non-atomic

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#15]
##### The problem:
Snapshots are not taken atomicly. Each object in the config file is taking individually.

###### Example:
DatasetA has a database
DatasetB has a file repository

A snapshot of DatasetA is taken
Both datasets are updated (database update, file added to repository)
A snapshot of DatasetB is taken
Your datasets are now out of sync. The database update is not saved, so the file added to the repo is orphaned.

###### Example 2:
DatasetA has a database
DatasetB has a file repository

A snapshot of DatasetB is taken
Both datasets are updated (database update, file added to repository)
A snapshot of DatasetA is taken
Your datasets are now out of sync. The database update is saved, but the file repo update is not, leaving orphaned data in the database. This is worse than the above.

##### Possible fix:
Take all the snapshots in a single command. As all the snapshots are pushed to an array n sanoid, this should need only minor changes near `system($zfs, "snapshot", "$snap");` This is also needs fixing in syncoid, something around `my $snapcmd = "$rhost $mysudocmd $zfscmd snapshot $fs\@$snapname\n";` This should not change expiring.

**Comment by redmop** [comment]
The above fix may bump up against the max shell length for many snapshots with long names. We have 2097152 characters to work with on linux according to `getconf ARG_MAX`

##### Sanoid fix:
Change the groupings in the config file to be logical groupings, and have a datasets entry specified as an option.
```
[VM_100]
	# space separated to make it easier to create command lines,
	datasets = "rpool/vm-100-disk-1 rpool/vm-100-disk-2"
	# or some other separator like ',' to handle datasets with spaces in the name
	datasets = "rpool/vm-100-disk-1,rpool/vm-100-disk-2"
	use_template = production
	recursive = yes
	process_children_only = yes
```

##### Syncoid fix:
Use recursive snapshots, and send/recv the whole thing all at once.

**Comment by jimsalterjrs** [comment]
I'm aware of this.  The problem with it is that you can have (and should 
be able to have) different snapshot *policies* for different datasets, 
which isn't possible if you take snapshots recursively for everything.

The fix only makes sense if you handle recursive definitions separately 
from multiple definitions, ie

    [pool/images]   template=production   recursive=yes

would take snapshots differently from

    [pool/images/A]   template=production[pool/images/B]  
    template=production

with interesting questions about what to do when you have a situation like

    [pool/images]
        template=production
        recursive=yes

    [pool/images/B]
        hourlies=0

That's not necessarily a [[wontfix]], but it is a 
[[wontfixwithoutmoney]]. =)

The value of snapshot atomicity across datasets is questionable, because 
a really hardcore insistence on atomicity across datasets implies that 
you don't ever want the datasets to be out of sync, which in turn raises 
the question "ok, why are these datasets separate in the first place?"  
There's nothing stopping you from putting the DB VM and the application 
VM in the same dataset, in which case snapshots are atomic to both VMs 
and any rollback will maintain consistency.  The only reason///to/ put 
the VMs in separate datasets is if you want to be able to break 
atomicity and roll back the fileserver without rolling back the DB, or 
vice versa.

If you want to take a crack at it yourself and submit patches, I will 
consider them for inclusion.

**Comment by redmop** [comment]
If the DB needs to be fast, it could be on a separate zpool as the the file repo, such as SSD and HDD.

The logic you have in the sanoid script is actually almost there. Instead of taking the snapshot lists and applying them individually, compile them together in one zfs snapshot $snap_list command. That would keep your policy structure, and it shouldn't change the config file structure.

Syncoid should be even easier. Make the snapshots recursive, and send/recv the whole thing at once.

I'll look at applying patches to fix this.

**Comment by jimsalterjrs** [comment]
You cannot make snapshots between separate zpools atomic, which would 
render the objection moot in this case.

**Comment by redmop** [comment]
Good point.

**Comment by jimsalterjrs** [comment]
Note that while not literally atomic, snapshots produced by Sanoid 
should already be *really freaking close* to atomic in human terms.

Keep in mind that Sanoid doesn't wait for the return of one snapshot 
before scheduling the next.  There is currently a one second sleep time 
between snapshots precisely because this ended up being a little 
problematic for sorting; the first set of snapshots for a given VM will 
usually include an hourly, daily, and monthly and if they're all the 
same YYYY-MM-DD-HH-MM-SS timestamp, you can't reliably get an answer to 
"which one is oldest" which can cause some wonkiness on down the road 
when you're trying to do things like "delete the oldest snapshots".

We could maybe figure out a better answer to that problem and eliminate 
the one second sleep, making snapshots 
still-not-technically-atomic-across-datasets-but-REALLY-close-now. If 
it's worthwhile.  That still falls in the category of 
[wontfixforfree,willacceptpatches] for me; 'cause my answer would still 
be "if they need to be atomic, they need to be in the same dataset".
