### ISSUE TITLE
Can't get syncoid to work

### ISSUE THREAD

**Issue by lockheed** [jimsalterjrs/sanoid#160]
Whatever, I try, I get the same result:
> # syncoid -sshport=2224  zroot/ROOT/default root@192.168.1.2:raid1/backup/juha_laptop/root
> Unknown cipher type 'chacha20-poly1305@openssh.com,arcfour'
> WARN: /usr/bin/lzop  not available on target ssh:-S /tmp/syncoid-root-root@192.168.1.2-1510081027 root@85.28.131.207 - sync will continue without compression.
> WARN: /usr/bin/mbuffer not available on target ssh:-S /tmp/syncoid-root-root@192.168.1.2-1510081027 root@192.168.1.2 - sync will continue without target buffering.
> Unknown cipher type 'chacha20-poly1305@openssh.com,arcfour'
> INFO: Sending oldest full snapshot zroot/ROOT/default@autosnap_2017-11-04_17:50:40_daily (~ 24.9 GB) to new target filesystem:
> Unknown cipher type 'chacha20-poly1305@openssh.com,arcfour'
> Unknown cipher type 'chacha20-poly1305@openssh.com,arcfour'
> mbuffer: error: outputThread: error writing to <stdout> at offset 0x0: Broken pipe
> mbuffer: warning: error during output to <stdout>: Broken pipe
> summary:  0.0 KiByte in  0.0sec - average of  0.0 KiB/s
>  154KiB 0:00:00 [5.30MiB/s] [>                                                                                                                                               ]  0%            
> CRITICAL ERROR:  /sbin/zfs send zroot/ROOT/default@autosnap_2017-11-04_17:50:40_daily | /usr/bin/pv -s 26685273432 | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/ssh -c chacha20-poly1305@openssh.com,arcfour -p 2224 -S /tmp/syncoid-root-root@192.168.1.2-1510081027 root@85.28.131.207 '  /sbin/zfs receive -F raid1/backup/juha_laptop/root' failed: 65280 at /usr/bin/syncoid line 218.

Mind you, lzop, mbuffer and pv are installed on both machines.

I tried doing it on default port 22, to eliminate the possibility of "sshport" being the culprit. No difference. It looks like it doesn't even connect to the remote host, even thous connecting with ssh works fine.

Any ideas?

**Comment by jimsalterjrs** [comment]
It tells you right there in the output, very first line: "Unknown cipher type 'chacha20-poly1305@openssh.com,arcfour'"

You're missing one or the other of those ciphers. You can specify a cipher your system supports manually using the -c argument to sanoid, or you can edit the default ciphers in sanoid itself pretty trivially so that you don't have to specify every time.

Future versions of sanoid will default to not specifying a cipher at all; in the past, SSH's default cipher was absolutely brutal on the CPU, so we defaulted to a "fast" cipher to eliminate the bottleneck. That is not the case any longer, though, so there's not much reason to always specify a non-default cipher anymore.

If you want a brain-dead simple way of figuring out what cipher your systems each support, just ``ssh -v otherbox`` and look at the output - it'll tell you what cipher they negotiate; you can specify that one.

**Comment by lockheed** [comment]
Wow, that was quick.

I inputed the command you mentioned to find out the cipher, but I don't think it showed it:

> # ssh -v root@192.168.1.2 -p 2224
> OpenSSH_7.6p1, OpenSSL 1.1.0g  2 Nov 2017
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: /etc/ssh/ssh_config line 53: Applying options for 192.168.1.2
> debug1: auto-mux: Trying existing master
> debug1: mux_client_request_session: master session id: 2
> Last login: Tue Nov  7 20:12:13 2017 from 37.47.102.151

**Comment by jimsalterjrs** [comment]
Try -vv. I think it's going to be aes128-cbc but I can't remember for sure 
off the top of my head.

**Comment by lockheed** [comment]
The output above was with -vv. 

I run a script checking available ciphers (here: https://superuser.com/questions/109213/how-do-i-list-the-ssl-tls-cipher-suites-a-particular-website-offers ) and it returned that none worked.
Strange.
