### ISSUE TITLE
sanoid failing due to empty lock file

### ISSUE THREAD

**Issue by jasonblewis** [jimsalterjrs/sanoid#165]
Recently I found sanoid was failing with a strange message:

```
Nov 20 12:31:14 quartz systemd[1]: Starting Run sanoid zfs snapshot tool...
Nov 20 12:31:14 quartz sanoid[19267]: error: process ID list syntax error
Nov 20 12:31:14 quartz sanoid[19267]: Usage:
Nov 20 12:31:14 quartz sanoid[19267]:  ps [options]
Nov 20 12:31:14 quartz sanoid[19267]:  Try 'ps --help <simple|list|output|threads|misc|all>'
Nov 20 12:31:14 quartz sanoid[19267]:   or 'ps --help <s|l|o|t|m|a>'
Nov 20 12:31:14 quartz sanoid[19267]:  for additional help text.
Nov 20 12:31:14 quartz sanoid[19267]: For more details see ps(1).
Nov 20 12:31:20 quartz sanoid[19267]: error: process ID list syntax error
Nov 20 12:31:20 quartz sanoid[19267]: Usage:
Nov 20 12:31:20 quartz sanoid[19267]:  ps [options]
Nov 20 12:31:20 quartz sanoid[19267]:  Try 'ps --help <simple|list|output|threads|misc|all>'
Nov 20 12:31:20 quartz sanoid[19267]:   or 'ps --help <s|l|o|t|m|a>'
Nov 20 12:31:20 quartz sanoid[19267]:  for additional help text.
Nov 20 12:31:20 quartz sanoid[19267]: For more details see ps(1).
```

after investigating I found that for some reason the the sanoid_cacheupdate.lock file was existing but 0 in size. I am not sure how this came about but I found there was no checking for such an occurence.

see around lines https://github.com/jimsalterjrs/sanoid/blob/master/sanoid#L937

**Comment by jimsalterjrs** [comment]
accepted PR to fix

**Comment by zeigerpuppy** [comment]
I am having this issue with Sanoid 2.0.0 (still using this version because of #469).

It only started happening a few days ago with no change to the sanoid config.
I was running a long resilver at the time which probably messed with the speed of the array but can't seem to resolve the issue.

I tried deleting the lock file(s) and ran sanoid multiple times but it only gets part way through the snapshots and then throws the empty lockfile error again.

**Comment by phreaker0** [comment]
@zeigerpuppy see #391, #468 and #473 for a proposed solution
