### ISSUE TITLE
syncoid fails on new snapshot with the same name as an existing snapshot

### ISSUE THREAD

**Issue by Siecje** [jimsalterjrs/sanoid#184]
I noticed that `syncoid` was failing to pull a snapshot called `beforeUpgrade` because it already had an older snapshot called `beforeUpgrade`.  I had deleted the snapshot on the main server but not on the backup server.

Can syncoid save the newer snapshot as `beforeUpgrade_1` or something?
Can it not fail to copy any of the other snapshots?

**Comment by Siecje** [comment]
It happened again, I deleted a snapshot and then re-created it.

Here is the error message.

```shell
cannot restore to data/images/$guest@$snapshot: destination already exists

CRITICAL ERROR: /usr/bin/ssh  -S /tmp/syncoid-root-root@$host root@$host ' /sbin/zfs send -I data/images/$guest@syncoid_$other_2018-02-06:15:01:47 data/images/$guest@syncoid_$other_2018-02-06:16:55:58
| /usr/bin/lzop  | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/lzop -dfc | /usr/bin/pv -s 4096
|  /sbin/zfs receive -F data/images/$guest failed: 256 at /usr/local/bin/syncoid line 327.
```

**Comment by rwarren** [comment]
@jimsalterjrs Although there is a clear ZFS-level problem with duplicate snapshot names, the fact that syncoid aborts on first failure does not seem like the safest behaviour.  We actually had a case where several datasets were not getting backed up as a result, just because they were alphabetically after the one with the duplicate snapshot name.  We needed to set up secondary backup checking to make sure that syncoid was doing its job properly. This is, of course, is a good idea anyway... but we were pushed there by this syncoid problem.

Ideally, my thinking is the behaviour would be that, on _any_ zfs sending error (eg: duplicate snapshot name) it would both:

1. Log an error indicating a syncing issue with that snapshot/dataset
2. Move on and complete the remaining snapshots (reporting errors on those if they have them)

**Comment by phreaker0** [comment]
@rwarren 
I'm experience the same error with duplicate snapshots on one system. So in the future I will try to come up with a solution which probably involves:

- check for zfs error reason
- rename the original snapshot on the target (probably suffix creation date)
- replicate again

But I don't know if this should be default or behaviour triggered by an extra flag.
@jimsalterjrs: can we reopen the issue, as this would be a nice feature?

**Comment by pavhofman** [comment]
Hi, please let me revive this thread. I also have this use case - gradually forwarding a snapshot of the same name, and syncoid (in zfs receive) failing to "fast-forward" the snapshot with "destination already exists".

I am a bit confused by @jimsalterjrs 's comment https://serverfault.com/a/999317 which kind of hints to  syncoid being able to detect the modified shapshots.

Please what is the recommended solution? Using unique snapshot names instead of "forwarding" a constant name?

Thanks a lot,

Pavel.

**Comment by phreaker0** [comment]
@pavhofman I currently use a risky option for my use case but this involves destroying the entire dataset at the target: https://github.com/jimsalterjrs/sanoid/blob/ef601eb96b016786af63ea5d7e30c8ad1b5de689/syncoid#L1978

**Comment by crsleeth** [comment]
Seeing this issue as well on a multi-year old 100 TB+ pool with multiple datasets where some datasets fail to sync due to daily snapshots already existing on the destination. Had to destroy the dupes on the destination manually then rerun the syncoid.
`cannot restore to tank/test@autosnap_2023-11-04_00:00:05_daily: destination already exists` using a simple `syncoid -r tank/test root@destination:tank/test`
