### ISSUE TITLE
Snapshot time should be in UTC

### ISSUE THREAD

**Issue by Siecje** [jimsalterjrs/sanoid#188]
Currently when the snapshots are created the time will be the local time.

https://github.com/jimsalterjrs/sanoid/blob/f6519c0aea4c624161f92a1304943d1c60e714bc/sanoid#L664

Is it possible to add a flag to use UTC time?

**Comment by Siecje** [comment]
You can set the default timezone to be `UTC` or set the TZ environment variable before running the command

`TZ=UTC sanoid ...`

**Comment by phreaker0** [comment]
thanks, didn't know one could switch to UTC, i made a PR to make it default

**Comment by Siecje** [comment]
When would you want to have local time?

If you are going to change the code why not change `localtime()` on the line above to `gmtime()`?

**Comment by Siecje** [comment]
@jimsalterjrs Is there a use case when you would want to use the local time?

Isn't it much cleaner to always use UTC in the code instead of having to set an environment variable?

**Comment by jimsalterjrs** [comment]
I'd personally prefer always using local time, because it matches up 
with expectations. Using UTC is more technically correct but in a 
local-only context (as opposed to in a datacenter with lots of clients 
all over the world) it's an extra lookup that frustrates you when you 
just want to roll back to / examine an hourly from yesterday without 
having to do any math. =)

**Comment by phreaker0** [comment]
@Siecje  In my case i use localtime on a fileserver where other (non technical) people can also access the ZFS snapshots for restoring deleted/modified files. For them it is much clearer to have the local time instead of UTC in the snapshot names.
