### ISSUE TITLE
syncoid not destroying ephemeral snapshots

### ISSUE THREAD

**Issue by toddpfaff** [jimsalterjrs/sanoid#195]
I'm finding lots of syncoid ephemeral snapshots being left behind.  Are these not supposed to be removed from both the source and target after the send-receive completes?

**Comment by toddpfaff** [comment]
I think I may have just clued in to what's happening.

I see that syncoid, when behaving correctly, retains the most recent ephemeral snapshot on both source and target.

However, in some cases, perhaps due to conflicts with sanoid runs, it doesn't always prune old ephemeral snapshots?  Does that sound correct?

If this is correct, what's the recommended way for sanoid and syncoid runs to coexist in order to avoid this problem?

Also, when one finds oneself in this state - with old ephemeral snapshot clutter - is there a recommended clean-up procedure?  A sanoid or syncoid option perhaps?

**Comment by toddpfaff** [comment]
Another curiosity related to ephemeral snapshots ... if I list snapshots on the target side, the USED column is always 0B, even when the USED column for the same snapshot on the sender side is not 0B.
Is this expected?

**Comment by jimsalterjrs** [comment]
Yes. A snapshot uses no space unless there is data that exists nowhere but 
in the snapshot (ie does not exist in the live filesystem either).

On a target, the only way data comes in is via replication, so the most 
recent snapshot will always show 0B used since it's identical to the live 
filesystem.

**Comment by jimsalterjrs** [comment]
A successful syncoid run will always purge all but the most recent syncoid 
snapshot *for that host*. No matter how many there are.

An unsuccessful syncoid run will leave the sync snapshot behind, because 
syncoid snapshots are *only* purged after successful replication.

If you have multiple hosts all syncing the same dataset, you'll end up with 
leftover syncoid snapshots that are never purged, because host A will purge 
its own old sync snapshots on both hosts A and B, but if host C has synced 
while any of host A's sync snapshots exist, host A will never see its sync 
snapshots on host C in order to purge them.

You can purge "foreign" sync snapshots manually or with a simple bash for 
loop or similar, or use no-sync-snap to avoid their creation in the first 
place if necessary.

**Comment by toddpfaff** [comment]
Thanks for the responses, Jim.

I can take this discussion elsewhere if you feel I'm abusing this open issue, but what I'm trying to achieve is to have an exact replica of my source zpools on target, including the backup history as produced by something like sanoid.  So what I'm looking for is the best combination of sanoid and syncoid to achieve that goal.  That seems to be not as straightforward as I had expected.

**Comment by toddpfaff** [comment]
Something just occurred to me ... for what I'm trying to achieve, does it make more sense to run sanoid with identical templates on both source and target, and then run syncoid with --no-stream to sync source to target?

**Comment by phreaker0** [comment]
@toddpfaff maybe I don't understand you problem fully, but what you want should be simple:
- run sanoid on the source host
- run syncoid for replication of source to target

if there are multiple syncoid snapshots, you should post the error output of syncoid when it fails
