### ISSUE TITLE
syncoid feature request: recursive replication

### ISSUE THREAD

**Issue by stevenolen** [jimsalterjrs/sanoid#2]
Would be great to support `zfs send -R` and `zfs send -r` to send descendant filesystems in one go!

http://docs.oracle.com/cd/E23824_01/html/821-1448/gbchx.html

**Comment by jimsalterjrs** [comment]
There's a reason syncoid isn't just using send -r - I discovered that in practice, you can easily end up with difficulties when new filesystems are created.  Keep in mind that one of the things syncoid must do is roll back target datasets if necessary to the exact condition of the newest matching snapshot with the source - this breaks horribly when you have child datasets that are created after the incremental replication has been ongoing for a while.

I do plan to implement recursive replication, but it's going to have to be more complicated than just tossing in the -r or -R arguments if it's to actually work properly and reliably, which is why it isn't already there. =)

I also plan to implement recursion in sanoid itself, so that you could for example have a single module definition for poolname/images which also covered poolname/images/image1, poolname/images/image2 ... etc, as long as the recursion flag is on for that module.

Real Soon Now (tm). =)

**Comment by jimsalterjrs** [comment]
In the meantime, you can do horrible, horrible hacks such as:

    for dataset in `ssh root@remotebox zfs list -o name -rH poolname/datasetname`; do echo syncoid root@remotebox:$dataset $dataset ; done

Obviously this presumes that `poolname/datasetname` is the same on both sides.

**Comment by stevenolen** [comment]
Thanks for the great detail! I look briefly at your code and thought that was the case, I'll wait patiently :+1:

**Comment by jimsalterjrs** [comment]
This is added and working.

`syncoid -r sourcepool/dataset targetpool/dataset`
