### ISSUE TITLE
Differing binary locations on hosts

### ISSUE THREAD

**Issue by jjlawren** [jimsalterjrs/sanoid#21]
I've been trying to get syncoid working between various hosts (and OS types), but the script seems to assume a standard binary layout across hosts. Unfortunately, some OSs have different conventions and package managers don't always make the same assumptions.

What about detecting binaries based on `$PATH`, using `which <executable>`?

A side benefit would reduce the need to modify the script itself on "non-standard" systems to keep git updates simpler.

**Comment by jimsalterjrs** [comment]
Path usually isn't set properly in a cron environment.

----------

(Sent from my phone - please blame any weird errors on autocorrect)

**Comment by jjlawren** [comment]
That's an easy fix, though. Could always use the hardcoded values as fallbacks.

**Comment by jimsalterjrs** [comment]
Would you send me the correct locations for your problem environment (I 
assume it's a Solaris variant?) please?

----------

(Sent from my phone - please blame any weird errors on autocorrect)

**Comment by jjlawren** [comment]
Some systems use `/opt/local` as a prefix, others use `/usr/local` or `/usr` as the base depending on the package manager. The path(s) can also change between script runs depending on the target host.

I've "fixed" the problem for the time being by setting the PATH env properly everywhere (cron & ssh) and removing absolute paths in the script.

**Comment by phryneas** [comment]
I created a bunch of symlinks to the expected locations but I'm not really a fan of that.

Here are my locations:

```
[root@vos] ~# ls -l `which zfs` `which ssh` `which ps` `which pv` `which mbuffer` `which sudo`
-r-xr-xr-x  1 root  wheel   41448 Dec 13 20:07 /bin/ps*
-r-xr-xr-x  1 root  wheel  102104 Dec 13 20:07 /sbin/zfs*
lrwxr-xr-x  1 root  wheel      22 Dec 15 21:13 /usr/bin/mbuffer@ -> /usr/local/bin/mbuffer
lrwxr-xr-x  1 root  wheel      17 Dec 15 21:12 /usr/bin/pv@ -> /usr/local/bin/pv
-r-xr-xr-x  2 root  wheel  183040 Dec 13 20:07 /usr/bin/ssh*
lrwxr-xr-x  1 root  wheel      19 Dec 15 21:13 /usr/bin/sudo@ -> /usr/local/bin/sudo
```

**Comment by otwieracz** [comment]
+1 here – this makes impossible to use sanoid on NixOS.
Solution which will be OK for me is to do in source code:
```
my $zfscmd = "/usr/bin/zfs"
my $localzfscmd = $zfscmd;
my $remotezfscmd = $zfscmd;
```

Then I will just replace $localzfscmd - this is very common case in NixOS to substitute paths in source code.

**Comment by fhriley** [comment]
Another vote for this. Syncoid can't be used on freenas either because of this.

**Comment by fhriley** [comment]
> Path usually isn't set properly in a cron environment.

Then check for the executable in path first and if not found, check in your default hardcoded locations. That way people can set the path correctly in the cron line and have the executables get picked up, but it's backwards compatible for people who have it in the hardcoded locations.

**Comment by jimsalterjrs** [comment]
I'll be working on this in the next day or two.  It's a deceptively difficult problem if you don't want to make every sync take that much longer / be that much more fragile, because you need to check for command paths not only on the local machine, but on one (possibly two) remote machines as well.  The additional overhead in remote calls to check paths can be significant.

I'm also going to work on fallback checks on SSH crypto, because testing against FreeBSD this morning made me aware that modern FreeBSD no longer supports arcfour by default.  I still want arcfour to be MY default, because it VERY significantly affects throughput on a LAN, but I'm planning to implement more intelligent behavior to fall back automatically to a mutually supported algorithm when necessary, which will also help out FreeBSD and FreeNAS users.

As always, thank you for the bug reports.  Your activity here makes the project better.

**Comment by jimsalterjrs** [comment]
I need to get this one knocked out with a solution proposed by @rlaager at the OpenZFS Dev Summit - push an append to the $PATH local and remote and then just issue the commands bare.
