### ISSUE TITLE
How do you list existing snapshots on local or remote and restore?

### ISSUE THREAD

**Issue by ovizii** [jimsalterjrs/sanoid#30]
Hi, I'm new to this, just reading up on it it sounds great but how do I list snapshots taken/synced by sanoid? How would I restore a specific snapshot? 

Or is that out of the scope of sanoid and needs to be done via the native builtin OS commands?

What exactly is findoid?

**Comment by jimsalterjrs** [comment]
Listing snapshots at the CLI is out of scope for sanoid.  `zfs list -t snapshot | grep autosnap` will show you everything taken by sanoid, or `zfs list -t snapshot | grep poolname/datasetname` if you want to see all snapshots (sanoid or not) whose parent is `poolname/datasetname`.

Findoid is a fledgling tool intended to find particular files present in QCOW2 format disk images, searching through all available zfs snapshots of a particular dataset for them.  It's likely not terribly useful in its current form; this is a pretty difficult task to get right due to needing to consider partitions (or the lack thereof), multiple possible filesystems, etc - particularly if you don't want to waste storage bandwidth needlessly looking through the wrong partition with each snapshot, etc etc etc.  This could eventually be pretty useful but right now, and in particular until I get the concept of the UI for the command right in my head, it's more of a proof-of-concept than anything.
