### ISSUE TITLE
Syncoid: Auto Adjusting Send Receive compression

### ISSUE THREAD

**Issue by redmop** [jimsalterjrs/sanoid#344]
Would it be a good idea to detect the source and destination compression, and if they are the same, disable syncoid compression and just tell zfs not to decompress/recompress the stream? If the source and destination have different compression, do the old way of send/compress/decompress/receive?

**Comment by jimsalterjrs** [comment]
Doesn't matter. Standard ZFS send decompresses data no matter what.
The "raw send" functionality included with the OpenZFS Encryption
patches will allow the ability to send a compressed dataset
still-compressed - and a raw send implies a "raw receive" as well, which
is what you're asking for here. 

A _normal_ ZFS send, which is all
syncoid is capable of doing at this point, will send data uncompressed
no matter whether it was compressed on-disk or not. Receive then obeys
the current dataset compression setting (for existing datasets) or the
parent compression setting (for new datasets created by full
replication), again regardless of what happened on the source. 

When
syncoid becomes capable of using raw send, you can specify compress=none
to avoid fruitlessly trying to recompress a dataset which is already
compressed ... and it would be a neat feature to automatically check for
already-compressed datasets to maybe not try to recompress them,
automatically. But none of this becomes relevant unless and until we're
using Tom Caputo's "raw send". 

On 2019-01-31 13:01, Shawn Perry wrote:


> Would it be a good idea to detect the source and destination
compression, and if they are the same, disable syncoid compression and
just tell zfs not to decompress/recompress the stream? If the source and
destination have different compression, do the old way of
send/compress/decompress/receive? 
> 
> --
> You are receiving this
because you are subscribed to this thread.
> Reply to this email
directly, view it on GitHub [1], or mute the thread [2].




Links:
------
[1]
https://github.com/jimsalterjrs/sanoid/issues/344
[2]

**Comment by redmop** [comment]
Ok. Just jumping the gun a bit. :)

**Comment by phreaker0** [comment]
@jimsalter I think you missed the compressed send in zfs 0.7.x (at least it's in the manpage for 0.7.12 and not in zfs 0.6.x). To be sure and because I was curious I just tried it (-c flag on zfs send) and it works. It will send the compressed stream, nothing is decompressed. For example with the current master you can use it like:
`syncoid --debug --sendoptions="-Lce" --compress=none src dst`

@redmop with #343 it will be easy to just check if the user supplied either -c (compressed send) or -w (raw send) and if so the source dataset could be checked for compression and the the pipe compression could be disabled (but only if the user didn't specify a compress option himself).

**Comment by jimsalterjrs** [comment]
You're right, I missed that. Does it use the existing on-disk
compression, or is that just ZFS doing the same thing Syncoid does, and
recompressing it for transmission, ala rsync -z? 

Also, does a zfs send
-c stream arriving at the target retain compression on disk, or does it
get decompressed in order to apply whatever compression setting is
present on the target?

**Comment by phreaker0** [comment]
As I understand the man page it sends the on disk compressed blocks as is.

Whats happening on the receiving side is indeed interesting, I didn't find it in the man page so I will check out it out and report back :-)

**Comment by phreaker0** [comment]
@jimsalter I tried and zfs will save the compressed blocks as they are, so they are not decompressed and compressed on the receiving side. I tested with gzip-9 on the sending side and disabled compression on the receiving side.

**Comment by jimsalterjrs** [comment]
@phreaker0 do we want to implement some kind of test functionality to check if the source is compressed on-disk and we're using ZFS > 0.7? Honestly this is pretty low priority for me, given that lzop is already so cheap it's effectively free. 

This strikes me as basically just being a mollyguard fencing off a pretty low impact potential mistake. There are more important mollyguards we could be working on =)

**Comment by phreaker0** [comment]
@jimsalterjrs I don't think it's worth the effort. In contrast to things like resume able send support this one can't be determined accurately. Let's say we have an uncompressed dataset with some data, the user switches the compression on later. If implemented we would now assume that the source is compressed and disable the compression but in this case the transfer will now need much more time as most of the data is really not compressed. Therefore I think this is the sole responsibility of the user to tell if syncoid should use compression or not as the user is the one who should know his datasets best.

**Comment by redmop** [comment]
@phreaker0 @jimsalterjrs I agree. Make a note about it (compression changes etc) in the docs and move on.

So support the -c option and allow disabling the compression pretty much covers this.

My original idea was to see if the source and destination were compressed the same way, then automatically put in the -c and don't bother with compressing the send/recv stream, but changing of compression not altering the data on disk sort of limit's that idea's usefulness. Good catch, @phreaker0.

**Comment by FunctionDJ** [comment]
in case another newbie like me comes across this:

i'm currently setting up truenas as a backup target and had lots of issues with permissions and warnings when trying to send snapshots using syncoid.

on my non-truenas source system that i want to send snapshots from syncoid tried to use `lzop` for compression but then printed a warning that it's not available on the target and that compression is disabled.

i couldn't figure out how to install `lzop` on truenas and even if it's possible, it seems like a regular truenas user isn't supposed to install global software like this anyway. so i checked what compression algorithms/programs are available to pass to syncoid's `--compression=...` argument and did some online searching and `zstd-fast` seems to be pretty good and it's also installed on truenas (installed binaries can typically be checked using `type zstd-fast` in the truenas shell).

so i'm using `zstd-fast` for now and it seems to work just fine.
