### ISSUE TITLE
Syncoid: Backup to file?

### ISSUE THREAD

**Issue by Eun** [jimsalterjrs/sanoid#35]
Hello there,
first of all: thanks for this great tool. :+1:   

But I have a problem: I have a backup destination that has no zfs installed, it is possible to use syncoid to backup the snapshots to file?

Best regards

Eun

**Comment by jimsalterjrs** [comment]
Hm - did Github eat my comment here?  I swear I gave a long, thoughtful reply to this BEFORE labeling it wontfix... let me recap:

The TL;DR is no, you can't use a raw file as a Syncoid target, and I'm highly unlikely to add that in as a feature since it would take you back to the Bad Old Days<tm> of fragile and bulky backup chains needing FULL-incremental-incremental-incremental-incremental-incremental-incremental for a week, then wipe that week and FULL-incremental-incremental-incremental-incremental-incremental-incremental all over again for the next week, with the destruction of any one incremental (or the full) making all of the rest of them useless.
