### ISSUE TITLE
Setup sanoid on FreeNAS?

### ISSUE THREAD

**Issue by apiening** [jimsalterjrs/sanoid#366]
I'm using sanoid on by debian production server to create snapshots.
I transfer them with syncoid to a FreeNAS machine as a backup.

Since I guess this might be a common setup, I wonder if sanoid can be installed on freenas to expire old snapthots.
Should a jail be used? What is the easiest way to get sanoid up and running under FreeNAS?

If there is another / simpler option to expire the snapshots on FreeNAS please give me a hint.

**Comment by jimsalterjrs** [comment]
It's been a hot minute since the last time I did it, but you can just install Sanoid on a FreeNAS instance the same as you would on a FreeBSD instance. I wouldn't bother with a jail, personally; just install the files to /usr/local/bin and /etc/sanoid and otherwise treat it just as you would a FreeBSD install (which for the most purposes is like a Linux install; you just have to do some hinky things regarding paths IIRC).

**Comment by apiening** [comment]
@jimsalterjrs Thank you, with a little bit of fiddling it worked!

For the record, I needed to do a `ln -s /usr/local/bin/perl /usr/bin/perl` so that the binary matched the expectation of sanoid and then I needed to install Config::IniFiles from cpan like this:
```
perl -MCPAN -e shell
cpan> install Config::IniFiles
```
and that's it.

**Comment by apiening** [comment]
Closing this issue since it is solved.
