### ISSUE TITLE
Request: NC support

### ISSUE THREAD

**Issue by dvaezazizi** [jimsalterjrs/sanoid#371]
Hey there,

Any plans to add netcat support in the near future? SSH is really slow when it comes to large datasets over 10/40gbe networks.

Thanks!

**Comment by mac-linux-free** [comment]
I would like to see it, too. Although SSH with AES-NI is acceptable fast over 10g.

**Comment by dvaezazizi** [comment]
I've utilized hpn patches for ssh, but still NC is much faster (2-3x) on 10/40+ gbe. 

Here are the commands I use if you wish to test:

send machine:
zfs send tank0/dataset@snap1 | mbuffer -q -s 128K -m 1G | pv -b | nc "target ip" 8000

receive machine:
nc -l 8000 | sudo mbuffer -q -s 128k -m 1G | pv -rtab | sudo zfs receive -vF tank0/dataset

**Comment by redmop** [comment]
mbuffer can do the job of nc here. 
mbuffer will need to be after pv though.

zfs send tank0/dataset@snap1 |  pv -b  | mbuffer -q -s 128K -m 1G -O <target ip>:<target port>
mbuffer -q -s 128k -m 1G -I <target port> | pv -rtab | sudo zfs receive -vF tank0/dataset

**Comment by danielewood** [comment]
I dont know if it would be a good idea to add this info to the readme since some alternative to SSH is often requested, but I needed to bypass encryption to enable syncing a 100+TB dataset over my SAN network at more then 80MB/sec. 

Setting up OpenSSH-HPN is as simple as the following:

```
yum -y group install 'Development Tools'
yum -y install zlib-devel openssl-devel
git clone https://github.com/rapier1/openssh-portable
cd openssh-portable/
autoreconf && ./configure
make -j$(grep -c '^physical id' /proc/cpuinfo)
```

Once that is done, connect to your server with the following to verify you can use the NONE cipher:
`./ssh $TARGET_SERVER -o NoneSwitch=yes -o NoneEnabled=yes echo "" | grep NONE`
You should then get:
`WARNING: ENABLED NONE CIPHER`

Once that is done, you can use the following settings to achieve quite impressive transfer speeds:
1. Edit syncoid to point to the absolute path of your newly compiled ssh client (I just made a temporary copy into the newly created openssh-portable directory)
2.  `/root/openssh-portable/syncoid --recursive --no-sync-snap --debug -o NoneSwitch=yes -o NoneEnabled=yes --compress=lz4 LOCAL_TANK root@TARGET_SERVER:TARGET_TANK`

With adding the LZ4 compression and unencrypted SSH, I was able to maintain an average of about 2Gbps line speed and about 350MB/sec write speed. The LZ4 compression made a huge difference in the overall transfer speed, even though it ate 75% of a 1.8GHz E5-2403v1 core.


FYI, FreeNAS 11.2U5 is running OpenSSH-HPN for its SSHd, but the ssh client is not:
```
ssh -v FREENAS_SERVER echo '' 2>&1 | grep -i hpn
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9-hpn14v15
debug1: match: OpenSSH_7.9-hpn14v15 pat OpenSSH* compat 0x04000000
```

**Comment by phreaker0** [comment]
@jimsalterjrs ping :-) My guess is you won't like this idea as the proposed rsh PR was denied as well, right?

**Comment by jimsalterjrs** [comment]
I would accept a cleanly implemented mbuffer or nc transport patch. But it needs to be clean, maintainable, and the invocation needs to make it very clear that you're foregoing any pretense of security to use it.

**Comment by jimsalterjrs** [comment]
Or are we just asking for docs on setting up a local cowboy SSH that includes null encryption and an option?

**Comment by jim-perkins** [comment]
> ./ssh $TARGET_SERVER -o NoneSwitch=yes -o NoneEnabled=yes echo "" | grep NONE

This does not work properly on ubuntu 20.04  .  What isnt clear is that the newly compiled sshd needs to be running on the remote end also, I believe.  if you run this command you will get the output 

    perkins@htpc:~/src/openssh-portable$ ./ssh localhost -o NoneSwitch=yes -o NoneEnabled=yes touch "zz" | grep NONE
    SSH: Server;Ltype: Version;Remote: 127.0.0.1-22;Protocol: 2.0;Client: OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
    WARNING: ENABLED NONE CIPHER
    Connection to localhost closed by remote host.

However you really never made a connection to the remote end ( which is running standard sshd )

and this is what is in the /var/log/auth.log on the remote (sshd) machine
    sshd[124029]: Unable to negotiate with user jperkins 127.0.0.1 port 35072: no matching cipher found. Their offer: none

**Comment by koraa** [comment]
You know there are ways of transmitting at high speeds securely; exchange symmetric keys over existing ssh connection, use libsodium, use multi threaded encryption…or try chacha12 if you really must. Even chacha20-poly1305@openssh.com might be worth a try…

Just using a transport over netcat seems like…an incomplete solution.

**Comment by beren12** [comment]
netcat is acceptable for secure networks, and on old machines even chacha is very slow.

**Comment by colttt** [comment]
so, it's still not implemented, right?
We would love this feature with netcat too

**Comment by phreaker0** [comment]
@colttt it's in v2.2.0 https://github.com/jimsalterjrs/sanoid/pull/513
