### ISSUE TITLE
syncoid syncs all snapshots, not just the ones created by sanoid

### ISSUE THREAD

**Issue by lckarssen** [jimsalterjrs/sanoid#42]
I'm not sure if this is a bug or a feature, but I noticed that syncoid syncs all snapshots between the source and destination. I expected it to only sync the ones created by sanoid (those whose names start with `autosnap`).

The reason why I'm reporting this is that I also have snapshots (not created by sanoid) that don't need to be replicated (e.g. snapshots that I take every 15 minutes).

I guess the simplest solution would be to do some grep-ing in the `getsnaps()` function, but maybe an option like `--only-autosnaps` would be more appropriate. Or, even more versatile: add an option to allow the user to select which snapshots to sync (e.g. something like: `--include-snap-type=weekly` that would only send snapshots named `autosnap_*_weekly`)

**Comment by jimsalterjrs** [comment]
It's a feature, but I admit I'd like to make it an *optional* feature 
eventually.

At the moment Syncoid uses the -I argument to replicate the full snapshot 
stream natively, which captures everything in a single ZFS operation. Doing 
what you're proposing requires performing the replication in multiple steps 
- an -i from @1 to @2, then from @2 to @3, then from @3 to @4, and so forth.

That *will* happen sometime fairly soon, though, since if like to be able 
to skip certain snapshots by pattern myself. It'll just be more complicated 
than it might have seemed at first blush, and I'm still deciding how I want 
to handle the progress meter properly.

----------

(Sent from my phone - please blame any weird errors on autocorrect)

**Comment by lckarssen** [comment]
Indeed, you are right, it is more complicated that I thought at first (and I didn't think of the progress bar at all :-)). 

In the mean time, I'll continue my test run of sanoid/syncoid. Thanks for both tools, so far they work well for my use case.

**Comment by mailinglists35** [comment]
> since if like to be able to skip certain snapshots by pattern myself.

I was going to file a feature request for this but searching the existing issues first revealed the discussion above. I don't mind sending more volatile snapshots as part of the whole send as long as the reference syncing snapshot is one of more long term type.

I'm thinking as a quick personal solution to hardcode syncoid to exclude my `zfs-auto-snap_hourly` and `zfs-auto-snap_frequently` from the list of candidates for `$oldestsnap` or `$newsyncsnap` (I prefer `zfs-auto-snapshot` for snapshot management)

I wish it was possible as an argument on command line to exclude sync candidates by a regex filter.

Shall we keep track of this wish here, or should I file a new issue ("_exclude candidates by regex filter_")?

**Comment by pgassmann** [comment]
This was implemented by #699 which added an `--exclude-snaps` option and an `--include-snaps` option.

This changes is not yet part of an official release, so you need to download the syncoid script from master: https://github.com/mr-vinn/sanoid/blob/master/syncoid
