### ISSUE TITLE
syncoid: sync zfs properties source -> target

### ISSUE THREAD

**Issue by fmyhr** [jimsalterjrs/sanoid#50]
At least part of this is just me getting my head around (and fighting) how zfs handles dataset mounting vs. how a "normal" Linux filesystem does it. I'm not a fan of datasets getting auto-mounted, particularly when using zfs /. So I tend to set canmount=noauto and/or mountpoint=legacy, or even canmount=off for datasets that are simply placeholders in the zfs name tree.

I notice that syncoid has getzfsvalue() and setzfsvalue() but doesn't currently use them. It would be nice imo if syncoid would set target properties (at least canmount & mountpoint) to match source dataset properties.

**Comment by jimsalterjrs** [comment]
It would be dangerous in the extreme to try to set mountpoint to match 
the source as opposed to wherever the default is.  Consider two sister 
servers, prod0 and prod1, that replicate to one another.  Each server 
might have data/images for its own local virtual machine images, and 
data/backup/images for its sister server's images as a replication 
target.  If syncoid automatically overwrote the default mountpoint 
property with the mountpoint property of the source, it would end up 
destroying production data on first replication.

Syncoid has getzfsvalue() and setzfsvalue() because it was manually 
setting datasets readonly during replication if they weren't already, 
then setting them back to their original value after replication had 
finished.  I ended up commenting the code out to do so due to apparent 
bugs in ZFS on Linux itself that were causing spurious errors, which 
seemed worse than the potential issues associated with *not* having the 
replication target set read-only during the replication.

**Comment by fmyhr** [comment]
Point taken, thank you for your reply & counter-example. This risk of auto-mounting in the wrong place is why I prefer to do things the old way: I use -O mountpoint=legacy when creating the zpool, and thankfully this is inherited by all child datasets. So there's little need (and much danger, as you point out) for syncing mountpoint from source -> target. I retract my request for that!

What about canmount? This defaults to 'on' and is NOT inherited by child datasets. If it has been set to 'off' or 'noauto' on the source, shouldn't that be copied to the target? Or could that also be dangerous?

**Comment by jimsalterjrs** [comment]
Interesting point on canmount, but I don't really feel that something that isn't mountable on the source would always necessarily need to be unmountable on the target.  Gonna wontfix that one until something more pressing on it changes my mind; thanks though.

**Comment by mailinglists35** [comment]
there are legitimate cases where the mountpoint is explicitly set instead of being inherited which makes the target (if is attached to the same machine) be mounted again on source mountpoint.

the workaround could be like this

```#!/bin/bash
CANMOUNT=$(zfs get -H canmount src | awk '{print $3}' )
zfs set canmount=noauto src
syncoid src dst
zfs set canmount=$CANMOUNT src
```

**Comment by mailinglists35** [comment]
@jimsalterjrs please reconsider this.
additionally to what I've said above, when I backup a dataset used by lxd I also need to backup it's mountpoint property. It would be a pain to manually restore mountpoint properties on restore from backup.
also there are user properties that are not transferred unless you do 'zfs send -p'

**Comment by mailinglists35** [comment]
hello Jim,
please reconsider this.
I totally forgot that sanoid can't transfer properties. now having to send again several Tb...  :-(

**Comment by mailinglists35** [comment]
@jimsalterjrs

**Comment by phreaker0** [comment]
@mailinglists35 take a look at #273, this should work for you
