### ISSUE TITLE
Feature Request: syncoid option to specify remote shell

### ISSUE THREAD

**Issue by Pyrroc** [jimsalterjrs/sanoid#531]
Given syncoid's failure to work on FreeNAS default root shell of /bin/csh when mbuffer is available, I would like to request a command line option to be able to specify a remote command shell to use when invoking ssh on the remote host. This would be pre-pended to the remote command invoked with ssh.

Rationale: Given that FreeNAS (or other setups) are considered appliances, it would be better to be able to leave the root shell at its default value and not require manually changing it which could possibly break appliance functionality that may rely on it remaining at the default value.

**Comment by phreaker0** [comment]
The problem with csh is that it doesn't support redirecting only stderr.
The problem with mbuffer could be solved easily I think because mbuffer has a switch to be quiet and suppress stderr output, so the redirection could be skipped. But stderr is also used in other parts of the code so it still will be unsupported.

Embedding all remote commands in another shell invocation level (and therefore another command escape iteration) would require much code changed and in my opinion is just not worth it. Best way I can think of is to create an replication user on FreeNAS and only change the login shell for this user.

@jimsalterjrs if you disagree, please reopen the ticket.
