### ISSUE TITLE
print() on closed filehandle FH at /usr/local/bin/sanoid line 1476

### ISSUE THREAD

**Issue by dlangille** [jimsalterjrs/sanoid#534]
I'm using Sanoid 2.0.3 on FreeBSD 12.1-RELEASE-p3

Conclusion: it's a `lockfile` issue, and you can't run monitor checks while something else is going on.

I noticed this today:

```
[dan@x8dtu:~] $ /usr/local/bin/sanoid --monitor-snapshots
print() on closed filehandle FH at /usr/local/bin/sanoid line 1476.
print() on closed filehandle FH at /usr/local/bin/sanoid line 1477.
Could not write to $cache!\n at /usr/local/bin/sanoid line 773.
```

Eh? So I tried:

```
[dan@x8dtu:~] $ sudo /usr/local/bin/sanoid --monitor-snapshots
OK: all monitored datasets (zroot, zroot/data, [etc...]) have fresh snapshots
```

A short while later:

```
[dan@x8dtu:~] $ /usr/local/bin/sanoid --monitor-snapshots
OK: all monitored datasets (zroot, zroot/data, [etc...]) have fresh snapshots
```

Looking at the code (https://github.com/jimsalterjrs/sanoid/blob/v2.0.3/sanoid#L1475) that's the `$lockfile`

 What's up with that?

**Comment by phreaker0** [comment]
You ordinary user can't write to the lockfile because it's probably owned by root, hence the error. Therefore it works when you run it as root. If the local cache of zfs snapshots is too old, --monitor-snapshots will attempt to update it and will write an update_cache lock, if already another sanoid instance holds the lock it will skip this and use the stale cache instead. So you can run sanoid --cron and sanoid --monitor-snapshots in parallel but they bot need permission to write to the same lockfile.
