### ISSUE TITLE
syncoid is destroying other snapshots

### ISSUE THREAD

**Issue by pboehm90** [jimsalterjrs/sanoid#558]
hello!
syncoid is desroying other snapshots i made after syncing:

(before sync)
`root@srv-backup:~# zfs list -t snapshot | grep backup-vm`
`tank/backup-vm@syncoid_dell2_2020-06-13:13:04:37       0B      -  1,60T  -`
`tank/backup-vm@aaa                                     0B      -  1,60T  -`

(after sync)
`root@srv-backup:~# zfs list -t snapshot | grep backup-vm`
`tank/backup-vm@syncoid_dell2_2020-06-13:13:12:35       0B      -  1,60T  -`

Conclusion: Snapshot 'aaa' was destroyed

I use this command to sync:
`syncoid tank/vm root@10.0.1.2:tank/backup-vm --source-bwlimit=40M`

i´ve tested with v.2.0.3 and the newest master

Best regards

**Comment by redmop** [comment]
This looks like you are showing snapshots on the destination. Is that correct?

**Comment by plex90** [comment]
@redmop 
Yes that`s correct

**Comment by secabeen** [comment]
By default, syncoid does a rollback before the send/receive to ensure that the receive will succeed. You can disable that with this argument:
`--no-rollback         Does not rollback clones or snapshots on target (it probably requires a readonly target)`

**Comment by plex90** [comment]
@secabeen 
Thanks for the hint but the result is the same :(
Do you guys make no own snapshits on the sync target?
Greetings

**Comment by secabeen** [comment]
@plex90 Try running with --debug, and it'll show the exact commands running on both sides.

**Comment by jimsalterjrs** [comment]
Syncoid rolling back is not the problem. Any successful ZFS replication must necessarily destroy any locally taken snapshots. For that matter, it must destroy **any** snapshots, from any source, which are newer than the first snapshot of the two snapshots defined in an internal replication.

For example, let's say you have snapshots @1 through @10 on a source, and @1 through @9 on a target. If you `zfs send -i pool/ds@5 pool/ds@10` on the source, when you `zfs receive` that incremental on the target, you will either lose @5 through @9 (if -F is used on the receive) or the replication will fail (because you have newer snapshots on the target).

If you do the same thing, but with -I (snapshot stream incremental) instead of -i (simple incremental), you STILL lose @5 through @9--but you get them back **after** losing them, because they're rebuilt using the stream you're receiving after being destroyed locally. (This still assumes you're using -F; otherwise, again, the replication just fails.)

Your choice is "take snapshots locally" or "replicate snapshots in from another source." You **cannot** have both, syncoid or no syncoid.

**Comment by pboehm90** [comment]
@jimsalterjrs 
Thank´s jim for the explaination! I´ll try to create all snapshots that i need on the source system and sync them to the destination.
