### ISSUE TITLE
sanoid is not pruning

### ISSUE THREAD

**Issue by yilmaz01** [jimsalterjrs/sanoid#570]

**Comment by John-KapitalYou** [comment]
I just noticed I had thousands (literally) of un-pruned snapshots that put my boot pool to 100% full.

I ran Sanoid manually to see what was going on, and it reported that "/var/run/sanoid_pruning.lock is invalid" when it got to the pruning stage.

I removed /var/run/sanoid_pruning.lock manually, and re-ran sanoid, and it started pruning again.

Could this be like the race condition one from a while back where the fix was that a stray pid file had to be auto-deleted? Should the same thing be done here?

Many thanks,
John.

**Comment by phreaker0** [comment]
I hope this will be resolved with 2.1.0 #601
