### ISSUE TITLE
Request to prevent stacking zero byte snapshots

### ISSUE THREAD

**Issue by Hr46ph** [jimsalterjrs/sanoid#571]
I would like to request whether it would be possible to give Sanoid a switch to rename the last snapshot if that one is still zero bytes, instead of creating a new one when its time for a new snapshot.

I don't think it matters for anything other than convenience; a clean list of snapshots without the clutter of several empty snapshots scattered throughout the list.

The reason for requesting this (as an option) is because I tend to work a lot on something for a while, and then won't touch it for weeks or months, or even a year while I work on other things. On some datasets I have snapshots every hour, others 4 times a day and yet others once a day. Retention varies too. Sanoid helps out since I can create the schedules and policies to fit the needs of each dataset, but I don't want to go through the hassle of changing these based on when I work on what and for how long. Hence, when I am not working on some data, Sanoid might create snapshots every day or every few hours while nothing is changing and its stacking zero byte snapshots for as long as the retention period. What makes this a hassle is that every once in a while, data does change and within that list of dozens of empty snaps is one with a change. Its inconvenient to go over the snapshot list. I resort to grepping and filtering and while that works (I know that's why those tools exist :P ), I think this for renaming instead of just stacking them would really come in handy in cases like my own.

For now, I run a daily cron job with a simple script to check the 'USED' field for the '0B' value and delete them. It helps with maintaining a relatively clean list.

Obviously if I'm missing something that would work better or if you believe Im doing something wrong I would love to hear it as well. Otherwise, would you consider this a feature request?

Thanks for reading!

**Comment by jimsalterjrs** [comment]
Renaming the snapshot won't change its creation time. Snapshot creation time is what sanoid uses to determine whether another snapshot needs to be taken according to policy.

Not taking snapshots because there haven't been any changes causes MANY complex follow-on issues, making it difficult to determine whether snapshots are being taken according to policy or not, whether new snapshots should or should not be taken, etc.

Absent some kind of very concrete working plan for dealing with this that doesn't make the whole system more fragile, having sanoid *not* adhere to its own policies and take snapshots when and as it should is unlikely to be a thing, sorry.
