### ISSUE TITLE
Description of Frequently Setting From sanoid.conf

### ISSUE THREAD

**Issue by JavaScriptDude** [jimsalterjrs/sanoid#594]
What is the `frequently` setting used for in sanoid.conf.

I cannot find any references in the `sanoid.defaults.conf`, `readme.md` or `man` page.

**Comment by secabeen** [comment]
It's in the current sanoid.defaults.conf:

# for snapshots shorter than one hour, the period duration must be defined
# in minutes. Because they are executed within a full hour, the selected
# value should divide 60 minutes without remainder so taken snapshots
# are apart in equal intervals. Values larger than 59 aren't practical
# as only one snapshot will be taken on each full hour in this case.
# examples:
# frequent_period = 15 -> four snapshot each hour 15 minutes apart
# frequent_period = 5 -> twelve snapshots each hour 5 minutes apart
# frequent_period = 45 -> two snapshots each hour with different time gaps
# between them: 45 minutes and 15 minutes in this case
frequent_period = 15

Here's the commit:
https://github.com/jimsalterjrs/sanoid/pull/157/commits/8bd98f18008494e27c47c6d16cc1fbbaec9a33a6

--Ted
