### ISSUE TITLE
Is there any risk to deleting empty (0B) autosnaps?

### ISSUE THREAD

**Issue by Dave--G** [jimsalterjrs/sanoid#616]
Not an issue, just a question:

Is there any risk to deleting empty (0B) snapshots created by sanoid?

My snapshot list is huge and I'm mulling using this:
https://gist.github.com/SkyWriter/58e36bfaa9eea1d36460
but am worried about unintended consequences.

Are there any downsides users should be aware of?  Will it negatively impact syncoid?

Great tools, thanks.

**Comment by redmop** [comment]
What is your pain here? Why do you feel the need to delete size zero snapshots? What is the gain by doing so?

No judgment, I'm trying to understand. Maybe I'll learn something.

**Comment by Dave--G** [comment]
on my system, which has a few filesystems with various policies, syncoid sources & destinations:
zfs list -t snap | wc -l returns 5449
zfs list -t snap | grep 0B | wc -l returns 3535
so about 65% of snapshots are empty.  Its a lot to wade through. (yes I know how to filter etc)
when the system is cold (relevant bits not in cache) zfs -t snap takes my system about 30 seconds to generate.

**Comment by jimsalterjrs** [comment]
As long as it shows 0B used, you won't lose any data removing them.

Just be careful you don't accidentally delete all *common* snapshots with a replication partner, or you'll break incremental replication between the two and have to start from scratch.

**Comment by Dave--G** [comment]
Closing this bug.

Suggestion to devs: Trimming 0B snapshots on the source filesystem just prior to syncoid replication seems benign (?) perhaps add it as an optional new feature?  It might be popular.

But I've decided that for now theres a low but still unacceptably high (non-zero) data risk that outweighs any benefit to this approach.  It's safer & easier to just filter output to work around the (non-)problem.

For convenience I ended up throwing a zls.sh file into /etc/profile.d/ that contains:

```
# convenience function to list all non-empty zfs snapshots
zls() {
  zfs list -t snap "$@" | sed '/ 0B /d'
}
export -f zls
```
This allows me to just do a `zls tank/share` or whatever and get the filtered results I'm looking for.

**Comment by jimsalterjrs** [comment]
Ok, I think you might be getting yourself into dangerous territory here. We need to clear this up a little further.

When you see 0B `USED` on a snapshot, that does **not** mean it's "empty." That means that there are no blocks present in that snapshot that are not present in at least one other snapshot (including the live filesystem).

It is "safe" to delete a **single** snapshot which has 0B `USED` without risk of losing data. But you can't delete another one "safely" until you do a new `zfs list` and recheck the `USED` for the **next** snapshot you're thinking of deleting.

If you write a terabyte of data, then take two snapshots--we'll call them @1 and @2--then delete the data, when you `zfs list` both @1 and @2 will show 0B `used`, since they each contain the same blocks. But if you destroy **both** of them, you will lose that terabyte of data forever--because once you destroyed @1, the `USED` on @2 changed to 1T, because @2 was now the only place that terabyte of data remained.

On top of all that, let's say you decide to filter out redundant snapshots on both the source and target of two replication partners. On the source, you deleted @1. On the target, you deleted @2. You didn't lose data on either--but you just broke your ability to replicate, because they don't have a common snapshot, even though they have the same data. 

At best, you'll needlessly have to roll back @2 on the target and re copy that whole 1T of data again from the source, using an earlier common snapshot that's still intact. If you didn't still have a common snapshot from **before** @1 and @2, you'll have to destroy the entire dataset on the target, and begin all over with a full replication of **all** data from the source.

**Comment by Dave--G** [comment]
Thanks for the clarification.  I dropped this idea because the data risk far outweighed any benefit and decided to just filter zfs list output instead (see my prior comment).

Suggest it might be a good idea to warn others away from this bad idea somewhere in the documentation.
