### ISSUE TITLE
CRITICAL ERROR: ssh connection echo test failed for user@computer with exit code 255 at /sbin/syncoid line 1498

### ISSUE THREAD

**Issue by s-a-p-i-e-n-s** [jimsalterjrs/sanoid#658]
```
[sapiens@discovery ~]$ sudo syncoid --sshport=222 rpool_wfg9sp sapiens@atlantis:western/backup/
sapiens@atlantis: Permission denied (publickey).
sapiens@atlantis: Permission denied (publickey).
CRITICAL ERROR: ssh connection echo test failed for sapiens@atlantis with exit code 255 at /sbin/syncoid line 1498.
```
However with `ssh -p 222 sapiens@atlantis` I am able to login perfectly well. I only have one ssh key on these systems!

**Comment by jimsalterjrs** [comment]
You published your `sapiens` ssh key to the remote system, not the `root` ssh key. But since you're calling `syncoid` with `sudo`, you're trying to authenticate using the `root` ssh key (if one exists), not the `sapiens` ssh key.

Either create a `root` ssh key and publish it to the other system, or use `sshoption` to point directly at the `sapiens` key even though you're running as `root`, not as `sapiens`.
