### ISSUE TITLE
syncoid "CRITICAL ERROR: Target exists but has no matching snapshots" but exits with 0

### ISSUE THREAD

**Issue by asmartin** [jimsalterjrs/sanoid#70]
I am running sanoid/syncoid 1.4.7 and attempting to pull VM snapshots from one server to another. This works well for most datasets, however I have at least one that exits with this error:

```
 # syncoid -r root@otherhost:storage/myvm storage/myvm ; echo $?

CRITICAL ERROR: Target exists but has no matching snapshots!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.

0
```

This would not be a problem, however you can see that syncoid is exiting with exit code 0, which is a problem since I cannot detect this failure. I see [in the code](https://github.com/jimsalterjrs/sanoid/blob/c1.4.7/syncoid#L712) that it is supposed to exit with code 256, but I am not sure why that is not occurring in this case. Any ideas?

**Comment by asmartin** [comment]
Any updates on this?

**Comment by jimsalterjrs** [comment]
Haven't the foggiest... if exit 256 doesn't exit 256, either you're not trapping errors right, or Perl has a bug, as far as I can tell!

**Comment by mailinglists35** [comment]
@jimsalterjrs in the code you are exiting 256 only if targetsize is less than 64M, but you print the error message earlier as the result of failing to find a matching common snapshot

in `sub getmatchingsnapshot` you have two cases where you exit unclean:
- no common snapshot
- target dataset size is used less than 64MB

the problem is that you only exit 256 on the second condition, but you print the message anyway for the first condition.

**Comment by jimsalterjrs** [comment]
this has since been fixed; turns out there are only 256 total exit codes available, and they start at 0... so `exit 256` is equivalent to `exit 0`.  Syncoid `exit 3`s on error now.  Whoops!

**Comment by mailinglists35** [comment]
> Syncoid exit 3

I'm looking at that latest syncoid but I see it returns 0

seems to be changed in commit https://github.com/jimsalterjrs/sanoid/commit/cf68e81d0352e8a1d9d564ce8ed56b2decc980a2#diff-47135678f850d0abfb421972ec7d3a03
from exit 3 to return 0

**Comment by jimsalterjrs** [comment]
The reason for that is documented in CHANGELIST.

**Comment by amartin3225** [comment]
Would it be possible to re-open this in order to implement exiting with 3 or a non-zero exit code if one of the datasets fails? My understanding of the changes in 1.4.13 is that you want to continue with the remaining datasets if one fails (which is good), but it is important to keep track of all of the return codes and then at the end exit with 3 if any one of them failed so that these failures are not silently lost.
