### ISSUE TITLE
How can I capture the output of syncoid so that I can send its output in an email?

### ISSUE THREAD

**Issue by UntouchedWagons** [jimsalterjrs/sanoid#714]
I want to have syncoid run every evening, that's easy enough but I'm not sure how to properly capture the output of syncoid to send in an email. I've tried this:

```
# RESULT=$(syncoid --no-sync-snap --skip-parent --recursive root@192.168.255.1:media vault/media)
# echo $RESULT
```

This sort of works but no newlines are printed so everything printed to stdout is one big line.

Any ideas?

**Comment by jimsalterjrs** [comment]
You don't really want the output of syncoid: what you want is to monitor how fresh the snapshots on the target are. If you have fresh snapshots, your replication is working properly. If you have stale snapshots only, your replication is not functioning properly.

This is what sanoid --monitor-snapshots is for:

~~~~
me@[redacted]-hs0:~$ sudo sanoid --monitor-snapshots
OK: all monitored datasets (data/images, data/images/apps-win10, data/images/fileserver, data/images/jabber, data/images/mailserver, data/images/pxeboot, data/images/qemu, data/images/quickbooks, data/images/unifi, data/images/webserver, data/images/wireguard) have fresh snapshots
~~~~

Sanoid.conf on the target decides what constitutes "fresh" and "stale" snapshots according to policy:

~~~~
me@[redacted]-dr0:~$ head -n3 /etc/sanoid/sanoid.conf
[data/images]
     use_template = backup
     recursive = yes
~~~~

So, we're using the `backup` template on all of our VM images, which are replicated in from prod. Let's look at our freshness policy defined in that template:

~~~~
me@[redacted]-dr0:~$ tail -n18 /etc/sanoid/sanoid.conf
[template_backup]
        hourly = 36
        daily = 30
        monthly = 3
        yearly = 0

        ### don't take snapshots - snapshots replicate in from source
        ### on backup datasets, they're not generated locally
        autosnap = no
        autoprune = yes

        ### monitor hourlies and dailies, but don't warn or
        ### crit until they're over 48h old, since replication
        ### is typically daily only
        hourly_warn = 2880
        hourly_crit = 3600
        daily_warn = 48
        daily_crit = 60
~~~~

There you have it--we'll throw a warning if the newest hourly or daily is more than 2880 minutes (48 hours) old, and throw a crit if the newest hourly or daily is 3600 minutes (60 hours) old. You can see this stuff commented more heavily for documentation in /etc/sanoid/sanoid.defaults.conf, if you care to look and better understand the individual settings like this.

There's a long delay here because this is the `backup` template, which expects new snapshots to be replicated in approximately once daily. The `production` and `hotspare` templates get excited considerably more quickly, since they expect snapshots to be taken (production) or replicated (hotspare) in much more frequently!
