### ISSUE TITLE
Skip taking a snapshot if no changes are detected

### ISSUE THREAD

**Issue by teambvd** [jimsalterjrs/sanoid#723]
I'd like the ability for sanoid's automated snapshot system to skip taking a snapshot if it detects that no changes have been made since the last snapshot was taken, ideally as a configuration setting that can be applied to any given template in sanoid.conf.

There are a couple methods that come to mind for this, but the easiest would seem to be using something like:
`zfs diff $LATESTSNAP $DATASET`

If this then returns anything other than null output, continue with taking the snapshot, else skip.

I could see this being handy for those taking snapshots at high frequency on datasets whose workloads are 'bursty', e.g. during business hours a specific share is relatively active with changes occurring every minute or more, while overnight there may only be 2-3 files modified as people remote in to complete whatever high urgency task they've got going on.

**Comment by jimsalterjrs** [comment]
You're welcome to submit your own patch for this as long as it's
non-default behavior and must obviously be opted into, but it's
definitely not something I'm going to devote any time to. 

First, there's effectively zero cost for a snapshot with no unique data;
second--and even more important--there's no easy way to see whether a
missed snapshot wasn't taken because no change in data, or wasn't taken
because something's broken. Breaking monitoring and alerting is a far
more serious problem than the occasional theoretically "unnecessary"
snapshot.
