### ISSUE TITLE
Race condition in sanoid? Can't recursively sync snapshots with syncoid due to different timestamps

### ISSUE THREAD

**Issue by csarn** [jimsalterjrs/sanoid#742]
I'm running sanoid 2.1.0 with the following config:

      [zroot/base/ubuntu]
        use_template = production
        recursive = yes
      [template_production]
        frequently = 4
        hourly = 12
        daily = 14
        weekly = 4
        monthly = 12
        yearly = 2
        autosnap = yes
        autoprune = yes

Important part: "recursive = yes". I want to then run 

    syncoid --sendoptions=Rw some_host:zroot/base/ubuntu backup/ubuntu

where I recursively fetch backups from that dataset.
This fails with:

    cannot send zroot/base/ubuntu@autosnap_2022-04-28_19:30:00_frequently recursively: snapshot zroot/base/ubuntu/home@autosnap_2022-04-28_19:30:00_frequently does not exist

and it does not exist because it has a different timestamp on the child dataset:

    # zfs list -t snapshot -o name |grep autosnap_2022-04-28_19:30
    zroot/base/ubuntu@autosnap_2022-04-28_19:30:00_frequently
    zroot/base/ubuntu/home@autosnap_2022-04-28_19:30:01_frequently

Notice the 1 second difference in timestamps. This is not how I expected this to work. Is there any way to make sanoid take recursive snapshots atomically? Like `zfs snapshot -r ...`?

**Comment by jimsalterjrs** [comment]
Change `recursive=yes` to `recursive=zfs` in your Sanoid policy.

Note that using ZFS recursion is more efficient, but less flexible—there are any number of ways doing zfs send -R can fail when you add or remove datasets after implementing a replication strategy using -R, which is why we don't use it by default!

Within those limits, `recursive=zfs` and `sendoptions=R` will do just what you want: take snapshots using ZFS recursion, and send them using ZFS recursion as well.
