### ISSUE TITLE
Cannot receive incremental stream: kernel modules must be upgraded to receive this stream

### ISSUE THREAD

**Issue by Derkades** [jimsalterjrs/sanoid#743]
The receiving system, this is where I ran the syncoid command, Ubuntu 22.04:
```
zfs-2.1.2-1ubuntu3
zfs-kmod-2.1.2-1ubuntu3
```

The sending system, Debian 11:
```
zfs-2.0.3-9
zfs-kmod-2.0.3-9
```

Shouldn't I be able to receive snapshots from ZFS 2.0 on a ZFS 2.1 system? This worked before, I'm not sure what happened. Probably not a Sanoid issue, but I am hoping that more people run into this issue and find this through google.

People have reported this happening when their kernel module version was not the same as their userspace tools version (not the case for me):
* https://www.reddit.com/r/zfs/comments/p11q9d/syncoid_stopped_working_after_upgrading_to_kernel/
* https://github.com/jimsalterjrs/sanoid/issues/665

Or when receiving unencrypted datasets into encrypted datasets in very old OpenZFS versions (I am receiving unencrypted datasets from an Ubuntu 20.04 system just fine):
* https://github.com/openzfs/zfs/issues/6574

**Comment by jimsalterjrs** [comment]
Certainly not a sanoid issue; this is an upstream OpenZFS issue and you should open a bug there: https://github.com/openzfs/zfs/issues

It could also be an Ubuntu-specific issue, in which case you'd want to file a bug on Launchpad: https://code.launchpad.net/ubuntu/jammy/amd64/zfsutils-linux

I'm going to go ahead and close this one, because there's nothing we can do about it here--but anyone encountering it who knows a mitigation is more than welcome to share it.
