### ISSUE TITLE
syncoid recursive replication prematurely aborts on first failure

### ISSUE THREAD

**Issue by rwarren** [jimsalterjrs/sanoid#80]
When syncoid encounters a problem during recursive replication, it fails out immediately. This is a pretty major bug since any subsequent datasets do not get backed up.

This was initially discovered/triggered in a situation where the destination had a dataset which no longer existed on the source (due to the source dataset being destroyed without updating the backup location).

**Comment by jimsalterjrs** [comment]
Fixed in 1.4.13.  Could honestly still use some extra love; right now syncoid will exit 0 after a failed replication and it should keep track of this kind of thing to make sure it exits with an error code if any dataset failed to replicate.  As it is now, it'll fail the one child replication, then continue on to successfully replicate the rest of the lot... but exit 0 when done, even though it DOES still whine piteously along the way.
