### ISSUE TITLE
syncoid: no tty or askpass

### ISSUE THREAD

**Issue by imad-abdou** [jimsalterjrs/sanoid#84]
hello

I am trying to push snapshots of LXD to backup host like this
$ sudo syncoid ebk-cts/containers/ebk-c1 ebkar@192.168.1.80:backup/ea

it says: Sending oldest full snapshot ebk-cts/containers/ebk-c1@syncoid_ebk_2017-05-07:14:50:51 (~ 1.8 GB) to new target filesystem:
sudo: no tty present and no askpass program specified

**Comment by jimsalterjrs** [comment]
You're attempting to run it as a non root user which doesn't have sudo 
without password privileges.

**Comment by remyd1** [comment]
Hi,

This issue is quite old, but I think it should not be necessary to run this program as root or sudo as zfs comes with "zfs allow" features ( https://docs.oracle.com/cd/E36784_01/html/E36835/gebxb.html#scrolltoc ), even if it is still not avalaible in ZoL in ubuntu repositories (but it is already present in the stable code; see : https://github.com/zfsonlinux/zfs/issues/4410 ).

So it would be great to make 'sudo' as an option.

Best regards,
Rémy
