### ISSUE TITLE
server A mirroring to B mirroring to C

### ISSUE THREAD

**Issue by candeynasa** [jimsalterjrs/sanoid#840]
I have server A mirroring to server B with syncoid and would like to copy to server C. Since server A is heavily used,I was thinking of copying B to C, rather than the more obvious A to C. Is this safe to do? What switches should I use?  Thanx

**Comment by rsysadmin-com** [comment]
I'm also trying to implement a similar mechanism:

serverA --push--> serverB

serverB  <--pull-- serverC

but when I run:

`syncoid --debug --no-privilege-elevation --create-bookmark --recursive syncoid@zfs-backup:BACKUPS/dataset PRODPOOL
`
I get a lot of

```
syncoid@zfs-node2:~$ syncoid  --no-privilege-elevation --create-bookmark --recursive syncoid@zfs-backup:BACKUPS/dataset ENGINE
cannot create snapshots : permission denied
CRITICAL ERROR: ssh      -S /tmp/syncoid-syncoid@zfs-backup-1691152397-6971 syncoid@zfs-backup  zfs snapshot ''"'"'BACKUPS/dataset'"'"''@syncoid_zfs-node2_2023-08-04:12:33:17-GMT00:00
 failed: 256 at /usr/sbin/syncoid line 1631.
cannot create snapshots : permission denied
CRITICAL ERROR: ssh      -S /tmp/syncoid-syncoid@zfs-backup-1691152397-6971 syncoid@zfs-backup  zfs snapshot ''"'"'BACKUPS/dataset/logs'"'"''@syncoid_zfs-node2_2023-08-04:12:33:17-GMT00:00
 failed: 256 at /usr/sbin/syncoid line 1631.
```
 
 despite I have granted the syncoid user all the needed permissions via:
 
` zfs allow -u syncoid compression,mountpoint,create,mount,receive,rollback,destroy PRODPOOL
` 
 on server-C pulling the snapshots
 
Any ideas? Am I overseeing the obvious?

TIA!

**Comment by jimsalterjrs** [comment]
> I have server A mirroring to server B with syncoid and would like to copy to server C. Since server A is heavily used,I was thinking of copying B to C, rather than the more obvious A to C. Is this safe to do? What switches should I use? Thanx

I generally recommend against doing it this way, because this makes B a single point of failure for C. If something goes wrong on B, instead of not having fresh backups on B, you won't have them on C *either.*

If you still want to do it that way, the most important thing is turning --no-sync-snap on for at least the A-->B replication, if not both. Otherwise, you'll end up having C get clogged up with foreign (created for the A-->B replication) sync snapshots, and you'll have to script something to purge those manually.

**Comment by jimsalterjrs** [comment]
> on serverC, I get a lot of
> 
> ````cannot create snapshots : permission denied````
>
> despite I have granted the syncoid user all the needed permissions via:
>
> zfs allow -u syncoid compression,mountpoint,create,mount,receive,rollback,destroy PRODPOOL

The error message told you what was missing: the `snapshot` permission, because you're choosing to use sync snaps. The part you haven't yet seen, but will once you `zfs allow -u syncoid snapshot PRODPOOL`, is where you'll also need to `zfs allow -u syncoid destroy PRODPOOL`, because syncoid needs to clean up old sync snapshots as well as create new ones.

It might be better to just use the `--no-sync-snap` argument to syncoid, which means you need neither the snapshot (pretty safe to grant) or destroy (danger, Will Robinson, danger!) permissions granted to your replication UID.
