### ISSUE TITLE
syncoid after sanoid process

### ISSUE THREAD

**Issue by madmax01** [jimsalterjrs/sanoid#854]
Hi Team,

how can i make sure a "syncoid" job runs right after the sanoid process was finished? i may overlooked the description for this

Appreciated

**Comment by jimsalterjrs** [comment]
Because all ZFS replication is snapshot-based, the best way to check proper completion of a syncoid run is to compare snapshots between source and target. You cannot have a partial snapshot or a corrupt snapshot, so if you see eg mypool/myds@2023-10-09_15:00:00_hourly on the target system, you know for a fact that it completed that backup run and has _all_ of the data from the source as of 3PM on 2023 October 09.

An even better way to check for this is to install and configure Sanoid on both ends. On the backup target end, Sanoid should be using the "backup" or "hotspare" templates, which do not attempt to take new snapshots, but DO monitor them. If you've properly configured that, you can issue a "sanoid --monitor-snapshots" to get a simple OK, WARN, or CRIT based on how new (or not-new) those snapshots are. Finally, if you want to get _real_ professional about it, you can use `sanoid --monitor-snapshots` (and its companion argument, `sanoid --monitor-health`) as a Nagios plugin, and get automated 24/7/365 alerting on both pool health and backup status.

**Comment by madmax01** [comment]
i try with post_snapshot_script = /etc/sanoid/syncoid.script.sh in the sanoid conf file

#!/bin/bash

syncoid  pool1 root@hostname:pool1/backup --no-resume --no-stream --insecure-direct-connection=ip:8888 --no-privilege-elevation --delete-target-snapshots --no-sync-snap --recursive

is this supported way?

**Comment by madmax01** [comment]
manual works. but when using the post_snapshot_script with same command and restart sanoid getting this error

mbuffer: warning: HOME environment variable not set - unable to find defaults file

**Comment by jimsalterjrs** [comment]
Ah, I misunderstood the initial question.

I would NOT advise running syncoid as a sanoid post script. Just create a separate cron job for syncoid, eg:

````
root@mybox:~# crontab -l
0 * * * * /usr/local/bin/syncoid -r my/stuff root@otherbox:~my/stuff

root@mybox:~#
````

**Comment by alexgarel** [comment]
@madmax01 systemd can be used for such things.

I use a timer for sanoid and define syncoid service with `After=sanoid.service`.
