### ISSUE TITLE
Sanoid Replication Issues

### ISSUE THREAD

**Issue by madmax01** [jimsalterjrs/sanoid#878]
Hi Team,

me getting following error

CRITICAL ERROR: Target pool1/backup/HOSTA/local_system exists but has no snapshots matching with pool1/local_system!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.

thats not right

checking HOSTA  with zfs list

HOSTA
pool1/local_system@autosnap_2023-12-23_00:00:01_daily

Sanoid Sync Server
pool1/backup/HOSTA/local_system@autosnap_2023-12-23_00:00:01_daily

is there an Bug? as from above i see valid Snapshots

sanoid --monitor-snapshots also give "OK: all monitored datasets xx have fresh snapshots"  on both sides

i don't understand the situation..... something not right.. have valid snaphots

how should be an snapshot newer on source then on sanoid sync server.... all configured with dayli snapshots... feels there is a missing logic if sync central server need always lower time then source

is it required on sync server to change the default a few min earlier? say 30m  same day?

**Comment by madmax01** [comment]
i tried now source 23:50 and target on 23:30 and trying syncoid on 23:59.. hope that will work as expected

**Comment by jimsalterjrs** [comment]
Are you running sanoid on both ends? If so, make sure sanoid on the target is NOT taking snapshots itself (eg don't use the production template).

**Comment by madmax01** [comment]
--no-resume --no-stream --no-privilege-elevation --recursive --no-sync-snap  --compress none 

i use this.. and i run command sync only on the "replication" box  to pull data

source host01 pool1/local_system@autosnap_2024-01-01_23:45:40_daily
replication  pool1/backup/host01/local_system@autosnap_2024-01-01_23:30:02_daily

also i don't understand those errors

replication must be to a NON EXISTENT DATASET, which will
                then be CREATED BY the initial replication process.
                
exists but has no snapshots matching with pool1!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.
                
                
all zfs entries where created init from syncoid.. but then stopped working and blames those exists.

Something is very strange

**Comment by madmax01** [comment]
for each of the sync entries it done i added to sanoid.conf the prune options..... is this wrong as you said "No template to use".. but if no template - how can i make sure those snapshots getting pruned?

**Comment by madmax01** [comment]
are you saying when i use this above > then no snapshots created... so no need to prune? do i need the bookmark?.. will test again as i think i saw snapshots created with above... or an error telling there is no snapshot from local

**Comment by madmax01** [comment]
for the target (where i sync data too) - how can i make sure i can snapshot them.. as i want to run a kinda retention

source > target (replication)
target > local zfs snapshots  (autosnap+prune)

when i do the autosnap+autoprune on those which syncoid created on target > then i get those errors above...... which makes no sense to me......How can i resolve this case to have local retention extra......

**Comment by madmax01** [comment]
[data/images]
recursive = yes
process_children_only = yes
autosnap = yes
autoprune = yes

if i understand i can use this and it would then process all childs and recursive (but not data/images itself)

Hoping this is right ;)

**Comment by phreaker0** [comment]
This isn't really a issue with this project, your questions are around how ZFS really works and I think you should look into how ZFS replication and snapshots work in detail as it seems you miss some basics. syncoid is a tool to handle zfs send/recv easily.

some pointer to your questions:

- you can't snapshot the target dataset of you replication on your target host as syncoid will rollback to the source state to make a zfs replication possible
- so in your case, because you used "--no-sync-snap" for the replication you only have the sanoid managed snapshots which get pruned on your target
- if there isn't any snapshot witch is the same between the source zfs dataset and the target dataset replication is no longer possible with zfs. This is easily fixed by omitting the "--no-sync-snap" flag
- you should only use a prune policy for sanoid on your target for cleanup as snapshot taking is useless because it gets rolled back for the replication

**Comment by madmax01** [comment]
i was may not clear. what i'am trying to do is

A><B  Replication

But the data i have replicated i want to create extra snapshots (not replicated) acting as Retention.. how can i do that without sanoid gets confused? not sure why would be confused when telling what to exact replicate

**Comment by madmax01** [comment]
i have this

LOCAL:

[data]
frequently = 0
hourly = 0
daily = 7
monthly = 0
yearly = 0
autosnap = yes
autoprune = yes

[data/system]
frequently = 0
hourly = 0
daily = 7
monthly = 0
yearly = 0
autosnap = yes
autoprune = yes

[data/images]
frequently = 0
hourly = 0
daily = 7
monthly = 0
yearly = 0
autosnap = yes
autoprune = yes

-----------

Replication:

[data/backup]
recursive = yes
process_children_only = yes
frequently = 0
hourly = 0
daily = 7
monthly = 0
yearly = 0
autoprune = yes

**Comment by madmax01** [comment]
i would understand now:

- Local = snapshots getting created and autopruned (but no replication)
- replication = replication create snapshots during sync and with config it does autoprune for all recursive childrens

i deleted all snapshots and all datasets... now works

is that the way supported and ok? if not how can i change that

what i try to archive is

- replication
- but once data needed 3 days ago,... to go replication dataset and get data out (but need pruned)

**Comment by jimsalterjrs** [comment]
You can't take snapshots directly on a replication target, if you expect 
them to survive the next incoming replication. This is not something 
specific to sanoid, it's just how ZFS replication works.

Take your extra snapshots on the source, let them replicate in, then you 
can destroy them on the source if you like.

On the target, you should still run sanoid so that it will prune old 
snapshots for you. But it shouldn't TAKE new snapshots ON the target. You 
can either use the backup or hotspare templates included, or just study 
them to see what a sanoid.conf stanza on a replication target should look like.

**Comment by madmax01** [comment]
Replication:

[data/backup]
recursive = yes
process_children_only = yes
frequently = 0
hourly = 0
daily = 7
monthly = 0
yearly = 0
autoprune = yes

i don't do extra snapshots on the Target Replication. so the snapshots are there. (when doing the init sync it does created by itself the snapshots)
