### ISSUE TITLE
[syncoid] feature request: option to bypass ssh by using mbuffer -O / mbuffer -I direct send/receive

### ISSUE THREAD

**Issue by mailinglists35** [jimsalterjrs/sanoid#99]
I am sending to a remote slow cpu (odroid).
The network communication is already secured by openvpn, so I do not need to neither modify remote default openssh configuration to permit arcfour nor to even use another crypto layer at all (ssh).

Currently I'm sending like this:
- ssh into remote receiving machine
- launch `screen`
- launch `mbuffer` | `lzop` | `zfs receive`
- launch `zfs send` | `lzop` | `mbuffer` on sending machine

It would come very handy to be able to do this using syncoid, bypassing the ssh channel for zfs snapshot transmission and leaving the ssh channel only for launching remote commands.

**Comment by jimsalterjrs** [comment]
I don't think this is something I'm likely to implement personally. I'm sympathetic to your use-case but it sounds like a little more of a PITA and a niche use-case than I'm willing to take on for free.  (For me personally, I'm never using ZFS on anything that doesn't have enough horsepower to easily saturate a 100+ Mbps link using ssh.)

I've assigned it to you because I _will_ accept quality PRs if you feel like tackling it yourself.

I might suggest also just playing with the ssh cipher - odroid might have hardware offload for AES-256-CBC or similar; you might want to play around with that and see if you can find a win lurking somewhere.  Changing cipher would be *way* easier than providing an option to do a non-ssh transport.

**Comment by hrast01** [comment]
While not the answer you're looking for, you can also use the Openssh-HPN patch set to get multithreaded scp along with a none cipher.  In fact, I'm trying to figure out how to change the cipher on the command line so I can get somewhere closer to line speed over my 10GB link.

**Comment by jimsalterjrs** [comment]
@hrast01 

> In fact, I'm trying to figure out how to change the cipher on the command line so I can get somewhere closer to line speed over my 10GB link.

~~~~
syncoid -c none source/dataset root@remote:target/dataset
~~~~

Assuming, of course, that "none" is a valid cipher for your ssh executable.

**Comment by hrast01** [comment]
I figured it out, that's why I edited my comment to remove it.  And part of the OpenSSH-HPN patches is a NONE cipher.  Unfortunately, its not just as easy as setting the cipher, as they really don't want to be doing any auth over an unencrypted channel, so you have to pass an option (-o NoneSwitch=yes) in to do encrypted auth, but then transition to a none cipher.

**Comment by jimsalterjrs** [comment]
You're welcome to patch syncoid to take a `-o` argument which it passes along to ssh.  Wouldn't be super hard; following the code to handle the -c cipher argument should make it pretty clear how to hack it in.  If you do it cleanly and submit a pull request, I'll approve it to merge into master.

**Comment by hrast01** [comment]
I took a look at it and its an easy enough change to pass one option, but it turns out I need to pass multiple options into scp (-o NoneSwitch=yes AND -o NoneEnabled=yes), my Perl-fu is too weak to get it done.

**Comment by jimsalterjrs** [comment]
Can you not pass them comma-separated to SSH, ie -o NoneSwitch=yes,NoneEnabled=yes?
(I'm not sure off the top of my head; I rarely use -o stuff with SSH unless it's for multiplexing.)

**Comment by jimsalterjrs** [comment]
... looks like you can't; damn.

**Comment by redmop** [comment]
There is a workaround. https://www.digitalocean.com/community/tutorials/how-to-configure-custom-connection-options-for-your-ssh-client

That should get you what you want without changing sanoid/syncoid.

**Comment by hrast01** [comment]
As soon as I saw the link I realized that I could put them in the .ssh/config, thanks for reminding me of that.

**Comment by hrast01** [comment]
And stymied AGAIN by OpenSSH-HPN rules.  You can have "NoneEnabled yes" in .ssh/config, but "NoneSwitch=yes" **MUST** be passed on the command line, and not in the config file.  I'll go ahead and test my -o changes to syncoid and when they're working, setup a PR.

**Comment by redmop** [comment]
Bugger. at least you only need one -o now.

What if you setup syncoid to do (example) "-o NoneEnabled=yes,NoneSwitch=yes" then parse it out in syncoid to do "-o NoneEnabled=yes -o NoneSwitch=yes"

**Comment by hrast01** [comment]
That's where I was originally headed once I knew both were required.  I'm barely a passable Python scripter, and I just get lost with Perl.  I've uncovered yet another wrinkle where you can't set a cipher either with the NoneSwitch=yes option, it overrides the none cipher usage. So, you have to set $sshcipher = "" get it to work (or just remove it entirely).  I fight more with it later.

**Comment by redmop** [comment]
The $sshcipher also overrides whatever happens to be in the config file.



Shawn T Perry
Red Mop Computing Services
phone: 303-881-2623
email: shawn@redmop.com

**Comment by jimsalterjrs** [comment]
Accepted PR, opened #117 for possible future enhancement to allow multiple SSH options on the command line.
